// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "forge-std/Test.sol";
import "forge-std/console.sol";
import "../src/AckiNackiBridge.sol";
import "../src/DummyVerifier.sol";
import "poseidon-solidity/PoseidonT3.sol";

contract AckiNackiBridgeTest is Test {
    AckiNackiBridge public bridge;
    DummyVerifier public verifier;

    address public user1 = address(0x1);
    address public user2 = address(0x2);

    // Helper function to hash a single value using Poseidon
    function hashSingle(bytes32 value) internal pure returns (bytes32) {
        return bytes32(PoseidonT3.hash([uint256(value), uint256(0)]));
    }

    // Helper function to hash a string using Poseidon
    function hashString(string memory str) internal pure returns (bytes32) {
        return hashSingle(bytes32(bytes(str)));
    }

    event Deposit(
        bytes32 indexed commitment,
        bytes32 indexed commitmentWithAmount,
        uint256 leafIndex,
        uint256 amount,
        uint256 timestamp
    );

    event Withdrawal(
        bytes32 indexed nullifier,
        address indexed recipient,
        uint256 amount,
        uint256 timestamp
    );

    function setUp() public {
        // Deploy the real Halo2 verifier from bytecode
        bytes memory bytecode = vm.readFileBinary("verifier_bytecode.bin");
        address halo2VerifierAddr;
        assembly {
            halo2VerifierAddr := create(0, add(bytecode, 0x20), mload(bytecode))
        }
        require(halo2VerifierAddr != address(0), "Failed to deploy Halo2 verifier");

        // Deploy DummyVerifier wrapper with the real Halo2 verifier
        verifier = new DummyVerifier(halo2VerifierAddr);

        // Deploy bridge with verifier address
        bridge = new AckiNackiBridge(address(verifier));

        // Fund test users
        vm.deal(user1, 100 ether);
        vm.deal(user2, 100 ether);
    }

    // Helper function to create a valid proof for the dummy verifier
    // Returns a real Halo2 proof generated by the verifier-generator
    // This proof was generated for public inputs: [nullifier=12345, recipient=0xabcd, amount=1000, root=0x1234]
    function createValidProof() internal pure returns (bytes memory, bytes32) {
        // Real Halo2 proof (800 bytes) generated by snark-verifier-sdk
        bytes memory proof = hex"f20e288d96df76dc1d71d22523d738df8726390bd250c96fcd58a4b531e8f647d8c042a7427b959e540df82ea8e2dddf8728209741f36422ee40a80d8b772e1d5c9a2b9c365f3799c00db1e0d08b6bde77b6b0c018f5576508f0c5ac19daab62f892f401b7a48105cbb7e4f68435858d9314a9c39e64d4dc0427ee6857d3e94c4d4e41a45b27ed2802d2a1a4776a5dee43dcc001124e681728c43d810cc5f422b0ae94d1754a67d4a2b1d1d5bd97fdfbc40fd8736a62109d44d157044aea351be6e481188e977deecd7ea5d92ad53ac25bcaa121521e5de4621380f30ba00e171c8807b265d6f8c22c1c011b487efaf4d220d3949702f512a661de8ce61dc70ce46202fcb60cba17033b15f54005cdf8aec75dddaf15acbfe86e6de0c40139107e69622a30692b875ffda01aa400d1e04fa6e7e606bb2f7962e9e5cbbe93bf1e0000000000000000000000000000000000000000000000000000000000000000b6f8846b6c9dca150f2e9053e397163252312f71532fae8ab975a4c010731e2d0dbc93be2709d1ab86989ce442b19873d6c87beb699f4b2a88d7aeee74a2cf2265fba5a3ceb45055a7bfb25d88170d5ee4b93b324e87d4abd4ede9fad7d10422fadac4af41d76227ee29b776a02a592cab8ab3aee6aee5f436ff47a77225ce03cf28091704f2a789ea59474598b223b34a28e06e94cd2d59358e344058f57909e2c590b17cf17b9045e4fa4f09a53f71a472e5f1d5d5ff8cb27af69bc5fa1f02019b0489eac657cda7529e24f8eee50c426590a751628757c101fd4b60a3d3107be9f542b2532280611ec6a1cbe621e7e3d163b860ffb3ca9c7494bd35a6a00e7558b9698cdf2c09df6447ac32f9e995e53bb703e1432389463f965dd684de01cb2ba8cc7e97a68da40924e7bad19e6d5a9d9ae48de750a0e5a6f02b4ed4720bab3f6f1707c2d0e872ca2b4ef08b5a7ea756ba65f03f38236e6e005baeb1d11b8b85b9016778b8bd71da8b22aed7f3324cd3bfe0e5d91febbff26ca1e305751f6c99146faa5c3da4c2e1de5f985bd7bcc32894a4ff1678508a66042484cc7d53e7777e4162605c1d77ff0c62ab19d854ff755c326c4861516216deee3c5ee309";

        // The nullifier that this proof was generated for
        bytes32 nullifier = bytes32(uint256(12345));

        return (proof, nullifier);
    }

    // Helper to convert hex character to uint
    function fromHexChar(uint8 c) internal pure returns (uint8) {
        if (bytes1(c) >= bytes1('0') && bytes1(c) <= bytes1('9')) {
            return c - uint8(bytes1('0'));
        }
        if (bytes1(c) >= bytes1('a') && bytes1(c) <= bytes1('f')) {
            return 10 + c - uint8(bytes1('a'));
        }
        if (bytes1(c) >= bytes1('A') && bytes1(c) <= bytes1('F')) {
            return 10 + c - uint8(bytes1('A'));
        }
        revert("Invalid hex character");
    }

    // Convert hex string to bytes
    function fromHex(string memory s) internal pure returns (bytes memory) {
        bytes memory ss = bytes(s);
        require(ss.length % 2 == 0, "Hex string must have even length");
        bytes memory r = new bytes(ss.length / 2);
        for (uint256 i = 0; i < ss.length / 2; ++i) {
            r[i] = bytes1(fromHexChar(uint8(ss[2 * i])) * 16 + fromHexChar(uint8(ss[2 * i + 1])));
        }
        return r;
    }

    // Generate a real ZK proof using FFI to call Rust proof generator
    // The circuit computes: nullifier = Poseidon(withdrawal_hash, nullifier_preimage)
    function generateProof(
        uint256 withdrawalHash,
        uint256 nullifierPreimage,
        uint256 recipient,
        uint256 amount,
        uint256 root
    ) internal returns (bytes memory, uint256) {
        string memory proofFile = "./proof_temp.txt";

        // Generate proof and save to file
        string[] memory inputs = new string[](8);
        inputs[0] = "bash";
        inputs[1] = "../../scripts/generate_proof_to_file.sh";
        inputs[2] = vm.toString(withdrawalHash);
        inputs[3] = vm.toString(nullifierPreimage);
        inputs[4] = vm.toString(recipient);
        inputs[5] = vm.toString(amount);
        inputs[6] = vm.toString(bytes32(root));
        inputs[7] = "contracts/ethereum/proof_temp.txt";

        vm.ffi(inputs);

        // Read the proof from file
        string memory hexStringWithPrefix = vm.readLine(proofFile);

        console.log("Hex string length:", bytes(hexStringWithPrefix).length);

        // Strip "0x" prefix if present
        bytes memory hexBytes = bytes(hexStringWithPrefix);
        string memory hexString;
        if (hexBytes.length >= 2 && hexBytes[0] == '0' && hexBytes[1] == 'x') {
            // Skip first 2 characters
            bytes memory stripped = new bytes(hexBytes.length - 2);
            for (uint i = 0; i < stripped.length; i++) {
                stripped[i] = hexBytes[i + 2];
            }
            hexString = string(stripped);
        } else {
            hexString = hexStringWithPrefix;
        }

        // Compute expected nullifier using Poseidon
        uint[2] memory poseidonInputs;
        poseidonInputs[0] = withdrawalHash;
        poseidonInputs[1] = nullifierPreimage;
        uint256 nullifier = PoseidonT3.hash(poseidonInputs);

        // Convert hex string to actual bytes
        return (fromHex(hexString), nullifier);
    }
    
    function testDeposit() public {
        bytes32 commitment = hashString("test_commitment");
        uint256 amount = 1 ether;
        
        vm.startPrank(user1);
        
        // Expect the Deposit event
        vm.expectEmit(true, true, false, true);
        emit Deposit(
            commitment,
            bridge.hashPair(commitment, bytes32(amount)),
            0,
            amount,
            block.timestamp
        );
        
        bridge.deposit{value: amount}(commitment, amount);
        
        vm.stopPrank();
        
        // Verify state
        assertEq(bridge.nextIndex(), 1);
        assertEq(bridge.treasuryBalance(), amount);
        assertEq(bridge.getLeaf(0), commitment);
    }
    
    function testDepositMultiple() public {
        uint256 amount = 1 ether;

        for (uint256 i = 0; i < 5; i++) {
            bytes32 commitment = hashSingle(bytes32(i));

            vm.prank(user1);
            bridge.deposit{value: amount}(commitment, amount);

            assertEq(bridge.getLeaf(i), commitment);
        }

        assertEq(bridge.nextIndex(), 5);
        assertEq(bridge.treasuryBalance(), 5 ether);
    }

    function testDepositInvalidAmount() public {
        bytes32 commitment = hashString("test_commitment");
        
        vm.startPrank(user1);
        
        // Send different amount than specified
        vm.expectRevert(AckiNackiBridge.InvalidAmount.selector);
        bridge.deposit{value: 2 ether}(commitment, 1 ether);
        
        // Send zero amount
        vm.expectRevert(AckiNackiBridge.InvalidAmount.selector);
        bridge.deposit{value: 0}(commitment, 0);
        
        vm.stopPrank();
    }
    
    function testMerkleRootChanges() public {
        bytes32 root0 = bridge.getRoot();

        bytes32 commitment1 = hashString("commitment1");
        vm.prank(user1);
        bridge.deposit{value: 1 ether}(commitment1, 1 ether);

        bytes32 root1 = bridge.getRoot();
        assertFalse(root0 == root1, "Root should change after deposit");

        bytes32 commitment2 = hashString("commitment2");
        vm.prank(user1);
        bridge.deposit{value: 1 ether}(commitment2, 1 ether);

        bytes32 root2 = bridge.getRoot();
        assertFalse(root1 == root2, "Root should change after second deposit");
    }

    function testWithdrawal() public {
        // First, make a deposit
        bytes32 commitment = hashString("test_commitment");
        uint256 depositAmount = 1 ether;

        vm.prank(user1);
        bridge.deposit{value: depositAmount}(commitment, depositAmount);

        // Get the Merkle root after deposit
        bytes32 root = bridge.getRoot();

        // Generate real proof with private inputs
        uint256 withdrawalHash = 11111;
        uint256 nullifierPreimage = 22222;
        (bytes memory proof, uint256 nullifier) = generateProof(
            withdrawalHash,
            nullifierPreimage,
            uint256(uint160(user2)),
            depositAmount,
            uint256(root)
        );

        uint256 balanceBefore = user2.balance;

        // The nullifier is a public output computed from private inputs
        bridge.withdraw(payable(user2), depositAmount, root, bytes32(nullifier), proof);

        // Verify state
        assertEq(user2.balance, balanceBefore + depositAmount);
        assertEq(bridge.treasuryBalance(), 0);
    }
    
    function testWithdrawalDoubleSpendPrevention() public {
        // Make a deposit
        bytes32 commitment = hashString("test_commitment");
        uint256 amount = 1 ether;

        vm.prank(user1);
        bridge.deposit{value: amount}(commitment, amount);

        // Get the Merkle root after deposit
        bytes32 root = bridge.getRoot();

        // Generate real proof with private inputs
        uint256 withdrawalHash = 33333;
        uint256 nullifierPreimage = 44444;
        (bytes memory proof, uint256 nullifier) = generateProof(
            withdrawalHash,
            nullifierPreimage,
            uint256(uint160(user2)),
            amount,
            uint256(root)
        );

        // First withdrawal
        bridge.withdraw(payable(user2), amount, root, bytes32(nullifier), proof);

        // Try to use same proof again (same nullifier will be used)
        vm.expectRevert(AckiNackiBridge.NullifierAlreadyUsed.selector);
        bridge.withdraw(payable(user2), amount, root, bytes32(nullifier), proof);
    }

    function testWithdrawalInvalidRoot() public {
        // Make a deposit
        bytes32 commitment = hashString("test_commitment");
        uint256 amount = 1 ether;

        vm.prank(user1);
        bridge.deposit{value: amount}(commitment, amount);

        // Try to withdraw with wrong root
        (bytes memory proof, bytes32 nullifier) = createValidProof();
        bytes32 wrongRoot = hashString("wrong_root");

        vm.expectRevert(AckiNackiBridge.InvalidProof.selector);
        bridge.withdraw(payable(user2), amount, wrongRoot, nullifier, proof);
    }
    
    function testWithdrawalInsufficientTreasury() public {
        // Make a small deposit
        bytes32 commitment = hashString("test_commitment");
        uint256 depositAmount = 1 ether;

        vm.prank(user1);
        bridge.deposit{value: depositAmount}(commitment, depositAmount);

        // Get the Merkle root after deposit
        bytes32 root = bridge.getRoot();

        // Generate real proof with private inputs
        uint256 withdrawalHash = 55555;
        uint256 nullifierPreimage = 66666;
        (bytes memory proof, uint256 nullifier) = generateProof(
            withdrawalHash,
            nullifierPreimage,
            uint256(uint160(user2)),
            2 ether, // Trying to withdraw more than deposited
            uint256(root)
        );

        // Try to withdraw more than deposited
        vm.expectRevert(AckiNackiBridge.InsufficientTreasury.selector);
        bridge.withdraw(payable(user2), 2 ether, root, bytes32(nullifier), proof);
    }

    function testWithdrawalEmptyProof() public {
        // Make a deposit
        bytes32 commitment = hashString("test_commitment");
        uint256 amount = 1 ether;

        vm.prank(user1);
        bridge.deposit{value: amount}(commitment, amount);

        // Try to withdraw with empty proof
        bytes32 root = bridge.getRoot();
        bytes memory emptyProof = "";
        bytes32 nullifier = bytes32(uint256(0x9999)); // dummy nullifier

        vm.expectRevert(AckiNackiBridge.InvalidProof.selector);
        bridge.withdraw(payable(user2), amount, root, nullifier, emptyProof);
    }

    function testHashPairDeterministic() public {
        bytes32 left = hashString("left");
        bytes32 right = hashString("right");

        bytes32 hash1 = bridge.hashPair(left, right);
        bytes32 hash2 = bridge.hashPair(left, right);

        assertEq(hash1, hash2, "Hash should be deterministic");
    }

    function testHashPairOrderMatters() public {
        bytes32 left = hashString("left");
        bytes32 right = hashString("right");

        bytes32 hash1 = bridge.hashPair(left, right);
        bytes32 hash2 = bridge.hashPair(right, left);

        assertFalse(hash1 == hash2, "Hash order should matter");
    }
    
    function testGetLeafInvalidIndex() public {
        vm.expectRevert("Invalid index");
        bridge.getLeaf(0);

        // Add one leaf
        vm.prank(user1);
        bridge.deposit{value: 1 ether}(hashString("commitment"), 1 ether);

        // Should work for index 0
        bridge.getLeaf(0);

        // Should fail for index 1
        vm.expectRevert("Invalid index");
        bridge.getLeaf(1);
    }
    
    function testTreeFull() public {
        // This test would take too long with TREE_HEIGHT=20
        // So we just verify the error exists
        // In practice, you'd deploy a test version with smaller height

        // For now, just verify the contract has the error defined
        // by trying to trigger it (won't actually fill the tree)
        assertTrue(true);
    }

    function testInvalidVerifierAddress() public {
        vm.expectRevert(AckiNackiBridge.InvalidVerifier.selector);
        new AckiNackiBridge(address(0));
    }

    function testVerifierIntegration() public {
        // Test that the verifier is properly integrated
        assertEq(address(bridge.verifier()), address(verifier));
        assertEq(verifier.getPublicInputsCount(), 4);
    }

    function testVerifierRejectsEmptyProof() public {
        bytes memory emptyProof = "";
        uint256[] memory publicInputs = new uint256[](4);
        publicInputs[0] = uint256(bytes32(uint256(0x1111))); // nullifier
        publicInputs[1] = uint256(uint160(user2)); // recipient
        publicInputs[2] = 1 ether; // amount
        publicInputs[3] = uint256(bridge.getRoot()); // root

        (bool isValid, ) = verifier.verifyWithdrawalProof(emptyProof, publicInputs);
        assertFalse(isValid);
    }

    function testVerifierRejectsWrongProofLength() public {
        // Proof can be any length (it's cryptographic data)
        bytes memory shortProof = new bytes(32);
        uint256[] memory publicInputs = new uint256[](4);
        publicInputs[0] = uint256(bytes32(uint256(0x2222))); // nullifier
        publicInputs[1] = uint256(uint160(user2)); // recipient
        publicInputs[2] = 1 ether; // amount
        publicInputs[3] = uint256(bridge.getRoot()); // root

        (bool isValid, ) = verifier.verifyWithdrawalProof(shortProof, publicInputs);
        assertFalse(isValid);
    }

    function testVerifierRejectsInvalidPublicInputs() public {
        bytes memory proof = "dummy_proof";

        // Test with wrong number of public inputs (2 instead of 4)
        uint256[] memory wrongInputs = new uint256[](2);
        wrongInputs[0] = uint256(uint160(user2));
        wrongInputs[1] = 1 ether;

        (bool isValid, ) = verifier.verifyWithdrawalProof(proof, wrongInputs);
        assertFalse(isValid);
    }

    function testVerifierRejectsZeroRecipient() public {
        bytes memory proof = new bytes(64); // Valid length but dummy data
        uint256[] memory publicInputs = new uint256[](4);
        publicInputs[0] = uint256(bytes32(uint256(0x3333))); // nullifier
        publicInputs[1] = 0; // Zero recipient (invalid)
        publicInputs[2] = 1 ether; // amount
        publicInputs[3] = uint256(bridge.getRoot()); // root

        (bool isValid, ) = verifier.verifyWithdrawalProof(proof, publicInputs);
        assertFalse(isValid);
    }

    function testVerifierAcceptsValidProof() public {
        // Make a deposit first to have a valid root
        bytes32 commitment = hashString("test_commitment_verifier");
        vm.prank(user1);
        bridge.deposit{value: 1 ether}(commitment, 1 ether);

        // User knows private inputs (never revealed)
        uint256 withdrawalHash = 0x1234;
        uint256 nullifierPreimage = 0x5678;

        // Get current root
        bytes32 root = bridge.getRoot();

        // Generate real proof
        (bytes memory proof, uint256 nullifier) = generateProof(
            withdrawalHash,
            nullifierPreimage,
            uint256(uint160(user2)),
            1 ether,
            uint256(root)
        );

        // Public inputs/outputs: [nullifier, recipient, amount, root]
        uint256[] memory publicInputs = new uint256[](4);
        publicInputs[0] = nullifier; // public output
        publicInputs[1] = uint256(uint160(user2)); // recipient
        publicInputs[2] = 1 ether; // amount
        publicInputs[3] = uint256(root); // root

        // Verify proof
        (bool isValid, bytes32 returnedNullifier) = verifier.verifyWithdrawalProof(proof, publicInputs);
        assertTrue(isValid);

        // Verify nullifier is returned correctly
        assertEq(uint256(returnedNullifier), nullifier);
    }

    function testVerifierComputesNullifierCorrectly() public {
        // Make a deposit first to have a valid root
        bytes32 commitment = hashString("test_commitment_nullifier");
        vm.prank(user1);
        bridge.deposit{value: 1 ether}(commitment, 1 ether);

        // Get current root
        bytes32 root = bridge.getRoot();

        // User knows different private inputs
        uint256 withdrawalHash1 = 0x1111;
        uint256 nullifierPreimage1 = 0x2222;

        uint256 withdrawalHash2 = 0x3333;
        uint256 nullifierPreimage2 = 0x4444;

        // Generate real proofs
        (bytes memory proof1, uint256 nullifier1) = generateProof(
            withdrawalHash1,
            nullifierPreimage1,
            uint256(uint160(user2)),
            1 ether,
            uint256(root)
        );

        (bytes memory proof2, uint256 nullifier2) = generateProof(
            withdrawalHash2,
            nullifierPreimage2,
            uint256(uint160(user2)),
            1 ether,
            uint256(root)
        );

        // Public inputs for proof1
        uint256[] memory publicInputs1 = new uint256[](4);
        publicInputs1[0] = nullifier1; // public output
        publicInputs1[1] = uint256(uint160(user2)); // recipient
        publicInputs1[2] = 1 ether; // amount
        publicInputs1[3] = uint256(root); // root

        // Public inputs for proof2
        uint256[] memory publicInputs2 = new uint256[](4);
        publicInputs2[0] = nullifier2; // public output
        publicInputs2[1] = uint256(uint160(user2)); // recipient
        publicInputs2[2] = 1 ether; // amount
        publicInputs2[3] = uint256(root); // root

        // Verify both proofs return different nullifiers
        (, bytes32 returned1) = verifier.verifyWithdrawalProof(proof1, publicInputs1);
        (, bytes32 returned2) = verifier.verifyWithdrawalProof(proof2, publicInputs2);

        assertEq(uint256(returned1), nullifier1);
        assertEq(uint256(returned2), nullifier2);
        assertTrue(nullifier1 != nullifier2, "Different preimages should produce different nullifiers");
    }

    // Test just the proof verification
    function testProofVerificationOnly() public {
        // Use fixed values that match what we generate the proof for
        uint256 withdrawalHash = 12345;
        uint256 nullifierPreimage = 67890;
        uint256 recipient = 2;
        uint256 amount = 1000000000000000000;
        uint256 root = 0x05d8910571e1f1b616680718b431a71565180cfca4c89bb1a0fdc9740fc0349f;

        console.log("Generating proof for fixed inputs...");
        (bytes memory proof, uint256 nullifier) = generateProof(withdrawalHash, nullifierPreimage, recipient, amount, root);
        console.log("Proof size:", proof.length);
        console.log("Computed nullifier:", nullifier);

        // Call verifier directly
        uint256[] memory publicInputs = new uint256[](4);
        publicInputs[0] = nullifier;
        publicInputs[1] = recipient;
        publicInputs[2] = amount;
        publicInputs[3] = root;

        (bool isValid, bytes32 returnedNullifier) = bridge.verifier().verifyWithdrawalProof(proof, publicInputs);

        console.log("Verification result:", isValid);
        console.log("Returned nullifier:", uint256(returnedNullifier));

        assertTrue(isValid, "Proof should be valid");
        assertEq(uint256(returnedNullifier), nullifier, "Nullifier should match");
    }

    // End-to-end test: Deposit -> Generate Real Proof -> Withdraw
    function testEndToEndWithRealProof() public {
        // Step 1: Make a deposit
        uint256 depositAmount = 1 ether;
        bytes32 commitment = hashString("test_commitment_e2e");

        vm.startPrank(user1);
        bridge.deposit{value: depositAmount}(commitment, depositAmount);
        vm.stopPrank();

        // Get the Merkle root after deposit
        bytes32 root = bridge.getRoot();

        // Step 2: Prepare withdrawal parameters
        uint256 withdrawalHash = 12345; // Private input
        uint256 nullifierPreimage = 67890; // Private input
        address recipient = user2;
        uint256 withdrawAmount = depositAmount;

        console.log("Generating real ZK proof...");
        console.log("  Withdrawal Hash:", withdrawalHash);
        console.log("  Nullifier Preimage:", nullifierPreimage);
        console.log("  Recipient:", recipient);
        console.log("  Amount:", withdrawAmount);
        console.log("  Root:", uint256(root));

        // Step 3: Generate real ZK proof using FFI
        (bytes memory proof, uint256 nullifier) = generateProof(
            withdrawalHash,
            nullifierPreimage,
            uint256(uint160(recipient)),
            withdrawAmount,
            uint256(root)
        );

        console.log("Proof generated, size:", proof.length);
        console.log("Computed nullifier:", nullifier);
        console.log("First 32 bytes of proof:");
        console.logBytes32(bytes32(proof));

        // Step 4: Perform withdrawal with real proof
        uint256 recipientBalanceBefore = recipient.balance;

        console.log("Calling withdraw with:");
        console.log("  recipient:", recipient);
        console.log("  amount:", withdrawAmount);
        console.log("  root:", uint256(root));
        console.log("  nullifier:", nullifier);

        vm.startPrank(user1);
        bridge.withdraw(
            payable(recipient),
            withdrawAmount,
            root,
            bytes32(nullifier),
            proof
        );
        vm.stopPrank();

        // Step 5: Verify withdrawal succeeded
        uint256 recipientBalanceAfter = recipient.balance;
        assertEq(recipientBalanceAfter - recipientBalanceBefore, withdrawAmount, "Recipient should receive withdrawal amount");

        // Verify nullifier is marked as used
        assertTrue(bridge.isNullifierUsed(bytes32(nullifier)), "Nullifier should be marked as used");

        console.log("End-to-end test passed!");
    }
}

