// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "forge-std/Test.sol";
import "../src/AckiNackiBridge.sol";
import "../src/DummyVerifier.sol";
import "poseidon-solidity/PoseidonT3.sol";

contract AckiNackiBridgeTest is Test {
    AckiNackiBridge public bridge;
    DummyVerifier public verifier;

    address public user1 = address(0x1);
    address public user2 = address(0x2);

    // Helper function to hash a single value using Poseidon
    function hashSingle(bytes32 value) internal pure returns (bytes32) {
        return bytes32(PoseidonT3.hash([uint256(value), uint256(0)]));
    }

    // Helper function to hash a string using Poseidon
    function hashString(string memory str) internal pure returns (bytes32) {
        return hashSingle(bytes32(bytes(str)));
    }

    event Deposit(
        bytes32 indexed commitment,
        bytes32 indexed commitmentWithAmount,
        uint256 leafIndex,
        uint256 amount,
        uint256 timestamp
    );

    event Withdrawal(
        bytes32 indexed nullifier,
        address indexed recipient,
        uint256 amount,
        uint256 timestamp
    );

    function setUp() public {
        // Deploy verifier first
        verifier = new DummyVerifier();

        // Deploy bridge with verifier address
        bridge = new AckiNackiBridge(address(verifier));

        // Fund test users
        vm.deal(user1, 100 ether);
        vm.deal(user2, 100 ether);
    }

    // Helper function to create a valid proof for the dummy verifier
    // Returns the proof and the expected nullifier (public output)
    // The proof is cryptographic data, nullifier is computed from private inputs
    function createValidProof() internal view returns (bytes memory, bytes32) {
        // Private inputs (known only to user, never revealed)
        bytes32 withdrawal_hash = bytes32(uint256(0xabcd));
        bytes32 nullifier_preimage = bytes32(uint256(0xef01));

        // Compute nullifier (public output) using Poseidon
        bytes32 nullifier = bridge.hashPair(withdrawal_hash, nullifier_preimage);

        // Build proof: just the cryptographic proof data (placeholder for now)
        // In reality, this would be elliptic curve points, field elements, etc.
        bytes memory proof = abi.encodePacked(
            bytes32(uint256(0x1111)), // placeholder proof data
            bytes32(uint256(0x2222)),
            bytes32(uint256(0x3333))
        );

        return (proof, nullifier);
    }

    // Helper function to create a valid proof for a specific deposit
    // Returns the proof and the computed nullifier
    function createValidProofForDeposit(
        bytes32 withdrawal_hash,
        bytes32 nullifier_preimage
    ) internal view returns (bytes memory, bytes32) {
        // Compute nullifier (public output) using Poseidon
        bytes32 nullifier = bridge.hashPair(withdrawal_hash, nullifier_preimage);

        // Build proof: just cryptographic proof data (placeholder)
        // In reality, this would be generated by the ZK prover
        bytes memory proof = abi.encodePacked(
            bytes32(uint256(0x4444)), // placeholder proof data
            bytes32(uint256(0x5555)),
            bytes32(uint256(0x6666))
        );

        return (proof, nullifier);
    }
    
    function testDeposit() public {
        bytes32 commitment = hashString("test_commitment");
        uint256 amount = 1 ether;
        
        vm.startPrank(user1);
        
        // Expect the Deposit event
        vm.expectEmit(true, true, false, true);
        emit Deposit(
            commitment,
            bridge.hashPair(commitment, bytes32(amount)),
            0,
            amount,
            block.timestamp
        );
        
        bridge.deposit{value: amount}(commitment, amount);
        
        vm.stopPrank();
        
        // Verify state
        assertEq(bridge.nextIndex(), 1);
        assertEq(bridge.treasuryBalance(), amount);
        assertEq(bridge.getLeaf(0), commitment);
    }
    
    function testDepositMultiple() public {
        uint256 amount = 1 ether;

        for (uint256 i = 0; i < 5; i++) {
            bytes32 commitment = hashSingle(bytes32(i));

            vm.prank(user1);
            bridge.deposit{value: amount}(commitment, amount);

            assertEq(bridge.getLeaf(i), commitment);
        }

        assertEq(bridge.nextIndex(), 5);
        assertEq(bridge.treasuryBalance(), 5 ether);
    }

    function testDepositInvalidAmount() public {
        bytes32 commitment = hashString("test_commitment");
        
        vm.startPrank(user1);
        
        // Send different amount than specified
        vm.expectRevert(AckiNackiBridge.InvalidAmount.selector);
        bridge.deposit{value: 2 ether}(commitment, 1 ether);
        
        // Send zero amount
        vm.expectRevert(AckiNackiBridge.InvalidAmount.selector);
        bridge.deposit{value: 0}(commitment, 0);
        
        vm.stopPrank();
    }
    
    function testMerkleRootChanges() public {
        bytes32 root0 = bridge.getRoot();

        bytes32 commitment1 = hashString("commitment1");
        vm.prank(user1);
        bridge.deposit{value: 1 ether}(commitment1, 1 ether);

        bytes32 root1 = bridge.getRoot();
        assertFalse(root0 == root1, "Root should change after deposit");

        bytes32 commitment2 = hashString("commitment2");
        vm.prank(user1);
        bridge.deposit{value: 1 ether}(commitment2, 1 ether);

        bytes32 root2 = bridge.getRoot();
        assertFalse(root1 == root2, "Root should change after second deposit");
    }

    function testWithdrawal() public {
        // First, make a deposit
        bytes32 commitment = hashString("test_commitment");
        uint256 depositAmount = 1 ether;

        vm.prank(user1);
        bridge.deposit{value: depositAmount}(commitment, depositAmount);

        // Create valid proof
        (bytes memory proof, bytes32 nullifier) = createValidProof();
        bytes32 root = bridge.getRoot();

        uint256 balanceBefore = user2.balance;

        // The nullifier is a public output computed from private inputs
        bridge.withdraw(payable(user2), depositAmount, root, nullifier, proof);

        // Verify state
        assertEq(user2.balance, balanceBefore + depositAmount);
        assertEq(bridge.treasuryBalance(), 0);
    }
    
    function testWithdrawalDoubleSpendPrevention() public {
        // Make a deposit
        bytes32 commitment = hashString("test_commitment");
        uint256 amount = 1 ether;

        vm.prank(user1);
        bridge.deposit{value: amount}(commitment, amount);

        // First withdrawal
        (bytes memory proof, bytes32 nullifier) = createValidProof();
        bytes32 root = bridge.getRoot();

        bridge.withdraw(payable(user2), amount, root, nullifier, proof);

        // Try to use same proof again (same nullifier will be used)
        vm.expectRevert(AckiNackiBridge.NullifierAlreadyUsed.selector);
        bridge.withdraw(payable(user2), amount, root, nullifier, proof);
    }

    function testWithdrawalInvalidRoot() public {
        // Make a deposit
        bytes32 commitment = hashString("test_commitment");
        uint256 amount = 1 ether;

        vm.prank(user1);
        bridge.deposit{value: amount}(commitment, amount);

        // Try to withdraw with wrong root
        (bytes memory proof, bytes32 nullifier) = createValidProof();
        bytes32 wrongRoot = hashString("wrong_root");

        vm.expectRevert(AckiNackiBridge.InvalidProof.selector);
        bridge.withdraw(payable(user2), amount, wrongRoot, nullifier, proof);
    }
    
    function testWithdrawalInsufficientTreasury() public {
        // Make a small deposit
        bytes32 commitment = hashString("test_commitment");
        uint256 depositAmount = 1 ether;

        vm.prank(user1);
        bridge.deposit{value: depositAmount}(commitment, depositAmount);

        // Try to withdraw more than deposited
        (bytes memory proof, bytes32 nullifier) = createValidProof();
        bytes32 root = bridge.getRoot();

        vm.expectRevert(AckiNackiBridge.InsufficientTreasury.selector);
        bridge.withdraw(payable(user2), 2 ether, root, nullifier, proof);
    }

    function testWithdrawalEmptyProof() public {
        // Make a deposit
        bytes32 commitment = hashString("test_commitment");
        uint256 amount = 1 ether;

        vm.prank(user1);
        bridge.deposit{value: amount}(commitment, amount);

        // Try to withdraw with empty proof
        bytes32 root = bridge.getRoot();
        bytes memory emptyProof = "";
        bytes32 nullifier = bytes32(uint256(0x9999)); // dummy nullifier

        vm.expectRevert(AckiNackiBridge.InvalidProof.selector);
        bridge.withdraw(payable(user2), amount, root, nullifier, emptyProof);
    }

    function testHashPairDeterministic() public {
        bytes32 left = hashString("left");
        bytes32 right = hashString("right");

        bytes32 hash1 = bridge.hashPair(left, right);
        bytes32 hash2 = bridge.hashPair(left, right);

        assertEq(hash1, hash2, "Hash should be deterministic");
    }

    function testHashPairOrderMatters() public {
        bytes32 left = hashString("left");
        bytes32 right = hashString("right");

        bytes32 hash1 = bridge.hashPair(left, right);
        bytes32 hash2 = bridge.hashPair(right, left);

        assertFalse(hash1 == hash2, "Hash order should matter");
    }
    
    function testGetLeafInvalidIndex() public {
        vm.expectRevert("Invalid index");
        bridge.getLeaf(0);

        // Add one leaf
        vm.prank(user1);
        bridge.deposit{value: 1 ether}(hashString("commitment"), 1 ether);

        // Should work for index 0
        bridge.getLeaf(0);

        // Should fail for index 1
        vm.expectRevert("Invalid index");
        bridge.getLeaf(1);
    }
    
    function testTreeFull() public {
        // This test would take too long with TREE_HEIGHT=20
        // So we just verify the error exists
        // In practice, you'd deploy a test version with smaller height

        // For now, just verify the contract has the error defined
        // by trying to trigger it (won't actually fill the tree)
        assertTrue(true);
    }

    function testInvalidVerifierAddress() public {
        vm.expectRevert(AckiNackiBridge.InvalidVerifier.selector);
        new AckiNackiBridge(address(0));
    }

    function testVerifierIntegration() public {
        // Test that the verifier is properly integrated
        assertEq(address(bridge.verifier()), address(verifier));
        assertEq(verifier.getPublicInputsCount(), 4);
    }

    function testVerifierRejectsEmptyProof() public {
        bytes memory emptyProof = "";
        uint256[] memory publicInputs = new uint256[](4);
        publicInputs[0] = uint256(bytes32(uint256(0x1111))); // nullifier
        publicInputs[1] = uint256(uint160(user2)); // recipient
        publicInputs[2] = 1 ether; // amount
        publicInputs[3] = uint256(bridge.getRoot()); // root

        (bool isValid, ) = verifier.verifyWithdrawalProof(emptyProof, publicInputs);
        assertFalse(isValid);
    }

    function testVerifierRejectsWrongProofLength() public {
        // Proof can be any length (it's cryptographic data)
        bytes memory shortProof = new bytes(32);
        uint256[] memory publicInputs = new uint256[](4);
        publicInputs[0] = uint256(bytes32(uint256(0x2222))); // nullifier
        publicInputs[1] = uint256(uint160(user2)); // recipient
        publicInputs[2] = 1 ether; // amount
        publicInputs[3] = uint256(bridge.getRoot()); // root

        (bool isValid, ) = verifier.verifyWithdrawalProof(shortProof, publicInputs);
        assertFalse(isValid);
    }

    function testVerifierRejectsInvalidPublicInputs() public {
        bytes memory proof = "dummy_proof";

        // Test with wrong number of public inputs (2 instead of 4)
        uint256[] memory wrongInputs = new uint256[](2);
        wrongInputs[0] = uint256(uint160(user2));
        wrongInputs[1] = 1 ether;

        (bool isValid, ) = verifier.verifyWithdrawalProof(proof, wrongInputs);
        assertFalse(isValid);
    }

    function testVerifierRejectsZeroRecipient() public {
        bytes memory proof = new bytes(64); // Valid length but dummy data
        uint256[] memory publicInputs = new uint256[](4);
        publicInputs[0] = uint256(bytes32(uint256(0x3333))); // nullifier
        publicInputs[1] = 0; // Zero recipient (invalid)
        publicInputs[2] = 1 ether; // amount
        publicInputs[3] = uint256(bridge.getRoot()); // root

        (bool isValid, ) = verifier.verifyWithdrawalProof(proof, publicInputs);
        assertFalse(isValid);
    }

    function testVerifierAcceptsValidProof() public {
        // User knows private inputs (never revealed)
        bytes32 withdrawal_hash = bytes32(uint256(0x1234));
        bytes32 nullifier_preimage = bytes32(uint256(0x5678));

        // Compute nullifier (public output)
        bytes32 nullifier = bridge.hashPair(withdrawal_hash, nullifier_preimage);

        // Build proof: cryptographic proof data (placeholder)
        bytes memory proof = abi.encodePacked(
            bytes32(uint256(0xaaaa)),
            bytes32(uint256(0xbbbb))
        );

        // Public inputs/outputs: [nullifier, recipient, amount, root]
        uint256[] memory publicInputs = new uint256[](4);
        publicInputs[0] = uint256(nullifier); // public output
        publicInputs[1] = uint256(uint160(user2)); // recipient
        publicInputs[2] = 1 ether; // amount
        publicInputs[3] = uint256(bridge.getRoot()); // root

        // Verify proof
        (bool isValid, bytes32 returnedNullifier) = verifier.verifyWithdrawalProof(proof, publicInputs);
        assertTrue(isValid);

        // Verify nullifier is returned correctly
        assertEq(returnedNullifier, nullifier);
    }

    function testVerifierComputesNullifierCorrectly() public {
        // User knows different private inputs
        bytes32 withdrawal_hash1 = bytes32(uint256(0x1111));
        bytes32 nullifier_preimage1 = bytes32(uint256(0x2222));

        bytes32 withdrawal_hash2 = bytes32(uint256(0x3333));
        bytes32 nullifier_preimage2 = bytes32(uint256(0x4444));

        // Compute different nullifiers (public outputs)
        bytes32 nullifier1 = bridge.hashPair(withdrawal_hash1, nullifier_preimage1);
        bytes32 nullifier2 = bridge.hashPair(withdrawal_hash2, nullifier_preimage2);

        // Build proofs (placeholder)
        bytes memory proof1 = abi.encodePacked(bytes32(uint256(0xcccc)));
        bytes memory proof2 = abi.encodePacked(bytes32(uint256(0xdddd)));

        // Public inputs for proof1
        uint256[] memory publicInputs1 = new uint256[](4);
        publicInputs1[0] = uint256(nullifier1); // public output
        publicInputs1[1] = uint256(uint160(user2)); // recipient
        publicInputs1[2] = 1 ether; // amount
        publicInputs1[3] = uint256(bridge.getRoot()); // root

        // Public inputs for proof2
        uint256[] memory publicInputs2 = new uint256[](4);
        publicInputs2[0] = uint256(nullifier2); // public output
        publicInputs2[1] = uint256(uint160(user2)); // recipient
        publicInputs2[2] = 1 ether; // amount
        publicInputs2[3] = uint256(bridge.getRoot()); // root

        // Verify both proofs return different nullifiers
        (, bytes32 returned1) = verifier.verifyWithdrawalProof(proof1, publicInputs1);
        (, bytes32 returned2) = verifier.verifyWithdrawalProof(proof2, publicInputs2);

        assertEq(returned1, nullifier1);
        assertEq(returned2, nullifier2);
        assertTrue(nullifier1 != nullifier2, "Different preimages should produce different nullifiers");
    }
}

