// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * @title Halo2PoseidonVerifierTest
 * @notice Tests for the Halo2 DarkDEX Poseidon verifier (Acki Nacki circuit)
 * @dev Verifies a Halo2 proof generated using the Acki Nacki DarkDEX circuit
 *      (gosh_dark_dex_halo2_circuit). The circuit proves knowledge of a secret
 *      key sk_u such that:
 *        Poseidon(Poseidon(sk_u, 0), private_note_sum, token_type, sk_u) = digest
 *
 *      Public inputs (3 field elements, 96 bytes):
 *        [private_note_sum, token_type, digest]
 *
 *      Private inputs (known only to prover):
 *        sk_u = 23
 *
 *      The Halo2Verifier contract is deployed from pre-compiled bytecode
 *      because foundry's optimizer settings can strip inline assembly.
 */
contract Halo2PoseidonVerifierTest is Test {
    address public verifier;

    // The valid calldata (3 x 32-byte instances + 2080-byte proof) generated by halo2-verifier-gen
    bytes public validCalldata;

    // Expected calldata size: 3 instances * 32 bytes + 2656 bytes proof = 2752 bytes
    uint256 constant EXPECTED_CALLDATA_SIZE = 2752;
    // Number of public inputs (instance columns)
    uint256 constant NUM_INSTANCES = 3;
    // Size of instance data in bytes
    uint256 constant INSTANCE_SIZE = NUM_INSTANCES * 32; // 96 bytes

    function setUp() public {
        // Deploy the Halo2 verifier from pre-compiled bytecode
        bytes memory bytecode = vm.readFileBinary("test/halo2_verifier_bytecode.bin");
        address deployed;
        assembly {
            deployed := create(0, add(bytecode, 0x20), mload(bytecode))
        }
        require(deployed != address(0), "Failed to deploy Halo2Verifier");
        verifier = deployed;
        console.log("Halo2Verifier deployed at:", verifier);
        console.log("Verifier code size:", verifier.code.length);

        // Load proof calldata from file
        validCalldata = vm.readFileBinary("test/halo2_proof_calldata.bin");
        assertEq(
            validCalldata.length, EXPECTED_CALLDATA_SIZE, "Calldata should be 2752 bytes (96 instance + 2656 proof)"
        );
    }

    /// @notice Test that a valid Halo2 proof verifies successfully
    function test_ValidProofVerifies() public {
        (bool success,) = verifier.call(validCalldata);
        assertTrue(success, "Valid proof should verify successfully");
        console.log("Valid Halo2 DarkDEX proof verified successfully!");
    }

    /// @notice Test that a proof with wrong private_note_sum is rejected
    function test_WrongPrivateNoteSumReverts() public {
        bytes memory wrongCalldata = _copyCalldata();
        // Change private_note_sum (first 32 bytes) from 1000 to 999
        wrongCalldata[31] = bytes1(0xE7); // 999 = 0x3E7, was 0x3E8 (1000)

        (bool success,) = verifier.call(wrongCalldata);
        assertFalse(success, "Proof with wrong private_note_sum should be rejected");
        console.log("Wrong private_note_sum correctly rejected");
    }

    /// @notice Test that a proof with wrong token_type is rejected
    function test_WrongTokenTypeReverts() public {
        bytes memory wrongCalldata = _copyCalldata();
        // Change token_type (second 32 bytes, offset 32-63) from 1 to 2
        wrongCalldata[63] = bytes1(0x02); // was 0x01

        (bool success,) = verifier.call(wrongCalldata);
        assertFalse(success, "Proof with wrong token_type should be rejected");
        console.log("Wrong token_type correctly rejected");
    }

    /// @notice Test that a proof with wrong digest is rejected
    function test_WrongDigestReverts() public {
        bytes memory wrongCalldata = _copyCalldata();
        // Corrupt the digest (third 32 bytes, offset 64-95)
        wrongCalldata[64] = bytes1(uint8(wrongCalldata[64]) ^ 0xFF);

        (bool success,) = verifier.call(wrongCalldata);
        assertFalse(success, "Proof with wrong digest should be rejected");
        console.log("Wrong digest correctly rejected");
    }

    /// @notice Test that a corrupted proof is rejected
    function test_CorruptedProofReverts() public {
        bytes memory corruptedCalldata = _copyCalldata();
        // Corrupt a proof byte (after the 96-byte instance section)
        corruptedCalldata[INSTANCE_SIZE + 10] = bytes1(uint8(corruptedCalldata[INSTANCE_SIZE + 10]) ^ 0xFF);

        (bool success,) = verifier.call(corruptedCalldata);
        assertFalse(success, "Corrupted proof should be rejected");
        console.log("Corrupted proof correctly rejected");
    }

    /// @notice Test that empty calldata is rejected
    function test_EmptyCalldataReverts() public {
        bytes memory emptyCalldata = new bytes(0);
        (bool success,) = verifier.call(emptyCalldata);
        assertFalse(success, "Empty calldata should be rejected");
        console.log("Empty calldata correctly rejected");
    }

    /// @notice Test that truncated calldata (only instances, no proof) is rejected
    function test_TruncatedCalldataReverts() public {
        bytes memory truncatedCalldata = new bytes(INSTANCE_SIZE);
        for (uint256 i = 0; i < INSTANCE_SIZE; i++) {
            truncatedCalldata[i] = validCalldata[i];
        }

        (bool success,) = verifier.call(truncatedCalldata);
        assertFalse(success, "Truncated calldata should be rejected");
        console.log("Truncated calldata correctly rejected");
    }

    /// @dev Helper to copy validCalldata into a mutable bytes array
    function _copyCalldata() internal view returns (bytes memory) {
        bytes memory copy = new bytes(validCalldata.length);
        for (uint256 i = 0; i < validCalldata.length; i++) {
            copy[i] = validCalldata[i];
        }
        return copy;
    }
}

