#!/bin/bash
# End-to-End Test Script for Acki Nacki Bridge
# This script tests the complete deposit -> proof generation -> withdrawal flow

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$SCRIPT_DIR/contracts/ethereum"
DEPOSIT_PROVER_DIR="$SCRIPT_DIR/deposit-prover"
DATA_DIR="$SCRIPT_DIR/e2e_test_data"

# Load environment variables
if [ -f "$CONTRACTS_DIR/.env" ]; then
    source "$CONTRACTS_DIR/.env"
else
    echo -e "${RED}Error: .env file not found in contracts/ethereum/${NC}"
    exit 1
fi

# Validate required environment variables
if [ -z "$SEPOLIA_RPC_URL" ] || [ -z "$PRIVATE_KEY" ]; then
    echo -e "${RED}Error: SEPOLIA_RPC_URL and PRIVATE_KEY must be set in .env${NC}"
    exit 1
fi

# Create data directory
mkdir -p "$DATA_DIR"

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Acki Nacki Bridge - End-to-End Test                      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Step 0: Run Groth16 setup (always re-run to ensure keys match current circuit)
echo -e "${YELLOW}[0/7] Running Groth16 setup...${NC}"
GNARK_DIR="$DEPOSIT_PROVER_DIR/gnark-wrapper"
if [ ! -f "$GNARK_DIR/halo2_proof.json" ]; then
    echo -e "${RED}halo2_proof.json not found in $GNARK_DIR${NC}"
    echo "Please run a proof generation first to create a sample proof for setup."
    exit 1
fi
cd "$GNARK_DIR"
go run . setup
# Copy the generated Solidity verifier to the contracts directory
cp -f Groth16Verifier.sol "$CONTRACTS_DIR/src/Groth16Verifier.sol"
# Fix pragma and contract name for foundry compatibility
sed -i 's/pragma solidity \^0\.8\.0;/pragma solidity 0.8.19;/' "$CONTRACTS_DIR/src/Groth16Verifier.sol"
sed -i 's/contract Verifier {/contract Groth16Verifier {/' "$CONTRACTS_DIR/src/Groth16Verifier.sol"
sed -i 's/\/\/\/ @title Groth16 verifier template\./\/\/\/ @title Groth16 verifier generated by gnark./' "$CONTRACTS_DIR/src/Groth16Verifier.sol"
sed -i 's/\/\/\/ @author Remco Bloemen$/\/\/\/ @author Remco Bloemen (template), gnark (generated)/' "$CONTRACTS_DIR/src/Groth16Verifier.sol"
# Force fresh deployment since keys changed
rm -f "$DATA_DIR/deployment.json"
echo -e "${GREEN}✓ Groth16 setup complete (keys + Solidity verifier updated)${NC}"
echo ""

# Step 1: Deploy contracts to Sepolia (with real Groth16 verifier)
echo -e "${YELLOW}[1/7] Deploying Bridge Contract to Sepolia...${NC}"
cd "$CONTRACTS_DIR"

# Check if already deployed
if [ -f "$DATA_DIR/deployment.json" ]; then
    echo -e "${GREEN}Found existing deployment, loading addresses...${NC}"
    BRIDGE_ADDRESS=$(jq -r '.bridge_address' "$DATA_DIR/deployment.json")
    VERIFIER_ADDRESS=$(jq -r '.verifier_address' "$DATA_DIR/deployment.json")
    ORACLE_ADDRESS=$(jq -r '.oracle_address' "$DATA_DIR/deployment.json")
    echo "  Bridge: $BRIDGE_ADDRESS"
    echo "  Verifier: $VERIFIER_ADDRESS"
    echo "  Oracle: $ORACLE_ADDRESS"
else
    echo "Deploying new contracts with Groth16 verifier..."
    DEPLOY_OUTPUT=$(forge script script/DeployRealBridge.s.sol:DeployRealBridge \
        --rpc-url "$SEPOLIA_RPC_URL" \
        --broadcast \
        --private-key "$PRIVATE_KEY" \
        2>&1)

    echo "$DEPLOY_OUTPUT"

    # Extract addresses from deployment output
    VERIFIER_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "Groth16DepositVerifier deployed at:" | awk '{print $NF}')
    BRIDGE_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "AckiNackiBridge deployed at:" | awk '{print $NF}')
    ORACLE_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "MockBlockHeaderOracle deployed at:" | awk '{print $NF}')

    if [ -z "$BRIDGE_ADDRESS" ] || [ -z "$VERIFIER_ADDRESS" ] || [ -z "$ORACLE_ADDRESS" ]; then
        echo -e "${RED}Failed to extract contract addresses from deployment${NC}"
        exit 1
    fi

    # Save deployment info
    cat > "$DATA_DIR/deployment.json" <<EOF
{
  "bridge_address": "$BRIDGE_ADDRESS",
  "verifier_address": "$VERIFIER_ADDRESS",
  "oracle_address": "$ORACLE_ADDRESS",
  "network": "sepolia",
  "deployed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF

    echo -e "${GREEN}✓ Contracts deployed successfully!${NC}"
    echo "  Bridge: $BRIDGE_ADDRESS"
    echo "  Verifier: $VERIFIER_ADDRESS"
    echo "  Oracle: $ORACLE_ADDRESS"
fi

echo ""

# Step 2: Make a deposit
echo -e "${YELLOW}[2/7] Making Test Deposit...${NC}"

DEPOSIT_AMOUNT="100000000000000"  # 0.0001 ETH in wei (0.01 ETH / 100)

echo "Depositing 0.0001 ETH to bridge..."
DEPOSIT_TX=$(cast send "$BRIDGE_ADDRESS" \
    "deposit()" \
    --value "$DEPOSIT_AMOUNT" \
    --rpc-url "$SEPOLIA_RPC_URL" \
    --private-key "$PRIVATE_KEY" \
    --json)

DEPOSIT_TX_HASH=$(echo "$DEPOSIT_TX" | jq -r '.transactionHash')

if [ -z "$DEPOSIT_TX_HASH" ] || [ "$DEPOSIT_TX_HASH" = "null" ]; then
    echo -e "${RED}Failed to get deposit transaction hash${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Deposit transaction sent!${NC}"
echo "  TX Hash: $DEPOSIT_TX_HASH"

# Wait for transaction to be mined
echo "Waiting for transaction to be mined..."
sleep 10

# Get transaction receipt
RECEIPT=$(cast receipt "$DEPOSIT_TX_HASH" --rpc-url "$SEPOLIA_RPC_URL" --json)
BLOCK_NUMBER=$(echo "$RECEIPT" | jq -r '.blockNumber')
TX_INDEX=$(echo "$RECEIPT" | jq -r '.transactionIndex')

echo "  Block: $BLOCK_NUMBER"
echo "  TX Index: $TX_INDEX"

# Extract deposit ID from event logs
DEPOSIT_ID=$(echo "$RECEIPT" | jq -r '.logs[0].topics[1]' | xargs printf "%d")

echo -e "${GREEN}✓ Deposit confirmed!${NC}"
echo "  Deposit ID: $DEPOSIT_ID"

# Save deposit info
cat > "$DATA_DIR/deposit_info.json" <<EOF
{
  "tx_hash": "$DEPOSIT_TX_HASH",
  "block_number": "$BLOCK_NUMBER",
  "tx_index": "$TX_INDEX",
  "deposit_id": $DEPOSIT_ID,
  "amount": "$DEPOSIT_AMOUNT",
  "bridge_address": "$BRIDGE_ADDRESS"
}
EOF

echo ""

# Step 3: Fetch deposit event data and generate MPT proof
echo -e "${YELLOW}[3/7] Fetching Deposit Event Data...${NC}"

cd "$DEPOSIT_PROVER_DIR"

echo "Fetching event data and MPT proof from Ethereum..."
cargo run --release --example fetch_deposit_data -- \
    --tx-hash "$DEPOSIT_TX_HASH" \
    --contract "$BRIDGE_ADDRESS" \
    --rpc-url "$SEPOLIA_RPC_URL" \
    --output "$DATA_DIR/deposit_proof_input.json"

if [ ! -f "$DATA_DIR/deposit_proof_input.json" ]; then
    echo -e "${RED}Failed to fetch deposit event data${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Event data fetched successfully!${NC}"
echo "  Saved to: $DATA_DIR/deposit_proof_input.json"

echo ""

# Step 4: Test circuit with MockProver
echo -e "${YELLOW}[4/7] Testing Circuit with MockProver...${NC}"

echo "Running MockProver test (fast, no proof generation)..."
echo "Note: Using max-data-byte-len=2048 to accommodate large receipts"
cargo run --release --example test_with_real_data -- \
    --input "$DATA_DIR/deposit_proof_input.json" \
    --mock-only \
    --max-data-byte-len 2048

echo -e "${GREEN}✓ Circuit test passed!${NC}"

echo ""

# Step 5: Generate Halo2 ZK proof
echo -e "${YELLOW}[5/7] Generating Halo2 ZK Proof...${NC}"

# Delete any existing snark file for this deposit ID to force regeneration
# (gen_snark_shplonk loads existing files instead of regenerating)
OLD_SNARK="$DEPOSIT_PROVER_DIR/data/deposit_proof_${DEPOSIT_ID}.snark"
if [ -f "$OLD_SNARK" ]; then
    echo "Removing stale snark file: $OLD_SNARK"
    rm -f "$OLD_SNARK"
fi

echo "Generating SNARK proof (this may take several minutes)..."
cargo run --release --example test_with_real_data -- \
    --input "$DATA_DIR/deposit_proof_input.json" \
    --generate-proof \
    --output "$DATA_DIR/deposit_proof_output.json" \
    --max-data-byte-len 2048

if [ ! -f "$DATA_DIR/deposit_proof_output.json" ]; then
    echo -e "${RED}Failed to generate proof${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Proof generated successfully!${NC}"
echo "  Saved to: $DATA_DIR/deposit_proof_output.json"

echo ""

# Step 6: Wrap Halo2 proof in Groth16
echo -e "${YELLOW}[6/7] Wrapping Halo2 Proof in Groth16...${NC}"

cd "$DEPOSIT_PROVER_DIR"

# Extract deposit ID for snark file path
SNARK_FILE="data/deposit_proof_${DEPOSIT_ID}.snark"

if [ ! -f "$SNARK_FILE" ]; then
    echo -e "${RED}Snark file not found: $SNARK_FILE${NC}"
    exit 1
fi

# Export Halo2 proof to JSON format for gnark
echo "Exporting Halo2 proof for gnark..."
cargo run --release --example export_proof_for_gnark -- \
    --input "$SNARK_FILE" \
    --output "$GNARK_DIR/halo2_proof.json"

echo -e "${GREEN}✓ Halo2 proof exported for gnark${NC}"

# Generate Groth16 proof wrapping Halo2 verification
echo "Generating Groth16 proof..."
cd "$GNARK_DIR"
go run . prove halo2_proof.json

if [ ! -f "groth16_proof_bytes.hex" ]; then
    echo -e "${RED}Failed to generate Groth16 proof${NC}"
    exit 1
fi

# Read Groth16 proof bytes (288 bytes: 256 proof + 32 promise_commit)
PROOF_BYTES=$(cat groth16_proof_bytes.hex)

echo -e "${GREEN}✓ Groth16 proof generated (288 bytes)${NC}"

echo ""

# Step 6b: Set execution layer block hash on oracle
# On post-merge Ethereum, blockhash() returns the beacon block root, not the execution
# layer block hash (keccak256 of block header RLP). The Halo2 circuit proves the execution
# layer hash, so we need to set it on the MockBlockHeaderOracle.
echo -e "${YELLOW}[6b] Setting execution layer block hash on oracle...${NC}"

# Extract execution layer block hash from proof output
EXEC_BLOCK_HASH=$(python3 -c "
import json
with open('$DATA_DIR/deposit_proof_output.json') as f:
    d = json.load(f)
print('0x' + bytes(d['block_hash']).hex())
")

echo "  Block number: $BLOCK_NUMBER"
echo "  Execution layer block hash: $EXEC_BLOCK_HASH"

# Convert block number to decimal for cast
BLOCK_NUMBER_DEC=$(python3 -c "print(int('$BLOCK_NUMBER', 16))")

cast send "$ORACLE_ADDRESS" \
    "setBlockHash(uint256,bytes32)" \
    "$BLOCK_NUMBER_DEC" \
    "$EXEC_BLOCK_HASH" \
    --rpc-url "$SEPOLIA_RPC_URL" \
    --private-key "$PRIVATE_KEY" \
    2>&1

echo -e "${GREEN}✓ Block hash set on oracle${NC}"

echo ""

# Step 7: Submit withdrawal transaction
echo -e "${YELLOW}[7/7] Submitting Withdrawal Transaction...${NC}"

cd "$CONTRACTS_DIR"

# Get sender address from private key
SENDER_ADDRESS=$(cast wallet address "$PRIVATE_KEY")

echo "Withdrawing to: $SENDER_ADDRESS"
echo "Amount: 0.0001 ETH"
echo "Deposit ID: $DEPOSIT_ID"

# Prepare public inputs array
# [depositId, sender, amount, contractAddress]
PUBLIC_INPUTS="[$DEPOSIT_ID,$(cast --to-uint256 $SENDER_ADDRESS),$DEPOSIT_AMOUNT,$(cast --to-uint256 $BRIDGE_ADDRESS)]"

echo "Submitting withdrawal transaction..."
WITHDRAW_TX=$(cast send "$BRIDGE_ADDRESS" \
    "withdraw(address,uint256,uint256,uint256,bytes)" \
    "$SENDER_ADDRESS" \
    "$DEPOSIT_AMOUNT" \
    "$DEPOSIT_ID" \
    "$BLOCK_NUMBER" \
    "$PROOF_BYTES" \
    --rpc-url "$SEPOLIA_RPC_URL" \
    --private-key "$PRIVATE_KEY" \
    --json)

WITHDRAW_TX_HASH=$(echo "$WITHDRAW_TX" | jq -r '.transactionHash')

if [ -z "$WITHDRAW_TX_HASH" ] || [ "$WITHDRAW_TX_HASH" = "null" ]; then
    echo -e "${RED}Failed to submit withdrawal transaction${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Withdrawal transaction sent!${NC}"
echo "  TX Hash: $WITHDRAW_TX_HASH"

# Wait for confirmation
echo "Waiting for confirmation..."
sleep 10

# Check if withdrawal was successful
WITHDRAW_RECEIPT=$(cast receipt "$WITHDRAW_TX_HASH" --rpc-url "$SEPOLIA_RPC_URL" --json)
WITHDRAW_STATUS=$(echo "$WITHDRAW_RECEIPT" | jq -r '.status')

if [ "$WITHDRAW_STATUS" = "0x1" ]; then
    echo -e "${GREEN}✓ Withdrawal successful!${NC}"
else
    echo -e "${RED}✗ Withdrawal failed!${NC}"
    echo "$WITHDRAW_RECEIPT" | jq
    exit 1
fi

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  End-to-End Test PASSED! ✓                                ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Summary:"
echo "  Bridge Address: $BRIDGE_ADDRESS"
echo "  Deposit TX: $DEPOSIT_TX_HASH"
echo "  Deposit ID: $DEPOSIT_ID"
echo "  Withdrawal TX: $WITHDRAW_TX_HASH"
echo ""
echo "All test data saved to: $DATA_DIR"
echo ""
echo -e "${BLUE}View transactions on Etherscan:${NC}"
echo "  Deposit: https://sepolia.etherscan.io/tx/$DEPOSIT_TX_HASH"
echo "  Withdrawal: https://sepolia.etherscan.io/tx/$WITHDRAW_TX_HASH"

