[package]
name = "poseidon-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
itertools = "0.11"
rand_core = { version = "0.6", default-features = false, features = [
    "getrandom",
] }
rand = "0.8"
halo2-base = { version = "=0.5.0", features = ["halo2-axiom", "test-utils"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pse-poseidon = { git = "https://github.com/axiom-crypto/pse-poseidon.git" }
snark-verifier-sdk = { version = "=0.2.3", default-features = false, features = [
    "loader_evm",
    "loader_halo2",
    "halo2-axiom",
    "revm",
] }

[[bin]]
name = "generate-proof"
path = "src/bin/generate_proof.rs"

[[bin]]
name = "generate-verifier"
path = "src/bin/generate_verifier.rs"

[[bin]]
name = "generate-calldata"
path = "src/bin/generate_calldata.rs"

[[bin]]
name = "test-keccak-evm"
path = "src/bin/test_keccak_evm.rs"
