#!/usr/bin/env bash
# Deploy or redeploy the shellnet E2E bridge bundle end-to-end.
#
# Runs `compute_bridge_anchors --at-head` against live shellnet to derive
# GENESIS_LAST_SEEN_BLOCK_SEQNO / GENESIS_PREV_MAX_LEVEL_LAYER_HASH /
# GENESIS_BK_SET_COMMITMENT, deploys the bridge bundle via forge, extracts
# BRIDGE_ADDRESS from the broadcast record, rewrites the non-secret
# L${LEVEL}_config/env, and archives prior prover state.
#
# NOT IDEMPOTENT: every run broadcasts a new set of contracts and spends new
# nonces. Audit the Foundry broadcast record and latest/pending nonce before a
# retry. This is the flow described in
# crates/bridge-relayer-daemon/docs/live_relayer_bridge_verifyBlock_runbook.md §3.
#
# Usage:
#   LEVEL=1 PRIVATE_KEY=<burner> ./scripts/deploy_bridge_bundle.sh   # L1 anchor
#   LEVEL=2 PRIVATE_KEY=<burner> ./scripts/deploy_bridge_bundle.sh   # L2 anchor
#
# Inputs (env):
#   LEVEL                      1 or 2 (required)
#   CONFIRM_NEW_BRIDGE_DEPLOY  must equal DEPLOY_NEW_CONTRACTS
#   PRIVATE_KEY                Sepolia burner from runbook §1 (required)
#   SEPOLIA_RPC_URL            default: https://ethereum-sepolia-rpc.publicnode.com
#   BRIDGE_GQL_ENDPOINT        default: https://shellnet.ackinacki.org/graphql
#   BRIDGE_BK_SET_CONFIG       default: ./bk_set.shellnet.json
#                              (relative to crates/bridge-prover-libraries)
#   WITHDRAW_ACC_FR            authoritative AN bridge account field element;
#                              required and immutable after deployment
set -euo pipefail
set +x
umask 077

: "${LEVEL:?set LEVEL=1 or LEVEL=2}"
: "${PRIVATE_KEY:?set PRIVATE_KEY=<sepolia burner>}"
: "${WITHDRAW_ACC_FR:?set authoritative WITHDRAW_ACC_FR (or an explicit dummy for verifyBlock-only smoke)}"
[[ "${CONFIRM_NEW_BRIDGE_DEPLOY:-}" == DEPLOY_NEW_CONTRACTS ]] || {
  echo "Refusing broadcast: set CONFIRM_NEW_BRIDGE_DEPLOY=DEPLOY_NEW_CONTRACTS" >&2
  exit 2
}
[[ "$LEVEL" == 1 || "$LEVEL" == 2 ]] || {
  echo "LEVEL must be 1 or 2" >&2
  exit 2
}
SEPOLIA_RPC_URL="${SEPOLIA_RPC_URL:-https://ethereum-sepolia-rpc.publicnode.com}"
BRIDGE_GQL_ENDPOINT="${BRIDGE_GQL_ENDPOINT:-https://shellnet.ackinacki.org/graphql}"
BRIDGE_BK_SET_CONFIG="${BRIDGE_BK_SET_CONFIG:-./bk_set.shellnet.json}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PROVER_DIR="$REPO_ROOT/crates/bridge-prover-libraries"
CONTRACTS_DIR="$REPO_ROOT/contracts/ethereum"
GENESIS_ENV="$(mktemp -t genesis.XXXXXX.env)"
trap 'rm -f "$GENESIS_ENV"' EXIT

# ─── 1. Derive genesis anchors from live shellnet chain head ──────────────────
echo ">>> Computing genesis anchors (level=$LEVEL) against $BRIDGE_GQL_ENDPOINT"
cd "$PROVER_DIR/bridge-prover-lib"
BRIDGE_GQL_ENDPOINT="$BRIDGE_GQL_ENDPOINT" \
BRIDGE_BK_SET_CONFIG="$PROVER_DIR/${BRIDGE_BK_SET_CONFIG#./}" \
cargo run --release --quiet --bin compute_bridge_anchors -- \
  --at-head --level "$LEVEL" \
  > "$GENESIS_ENV"

echo ">>> Derived anchors:"
cat "$GENESIS_ENV"
set -a && source "$GENESIS_ENV" && set +a

# CRITICAL RENAME: compute_bridge_anchors emits GENESIS_SEED_SEQNO;
# DeployShellnetE2EBridge.s.sol reads GENESIS_LAST_SEEN_BLOCK_SEQNO via
# vm.envOr(..., 0) — without this alias the constructor silently pins 0.
export GENESIS_LAST_SEEN_BLOCK_SEQNO="$GENESIS_SEED_SEQNO"

# ─── 2. Deploy the bundle (14 CREATEs across 6 logical components) ────────────
cd "$CONTRACTS_DIR"
export PRIVATE_KEY
export WIRE_WITHDRAW_BY_PROOF=true
export WITHDRAW_ACC_FR

echo ">>> forge script DeployShellnetE2EBridge (chain 11155111)"
forge script script/DeployShellnetE2EBridge.s.sol:DeployShellnetE2EBridge \
  --rpc-url "$SEPOLIA_RPC_URL" --broadcast --slow

# ─── 3. Extract BRIDGE_ADDRESS from the broadcast record ──────────────────────
BROADCAST="$CONTRACTS_DIR/broadcast/DeployShellnetE2EBridge.s.sol/11155111/run-latest.json"
BRIDGE_ADDRESS="$(jq -r '
  .transactions[]
  | select(.contractName=="AckiNackiBridge" and .transactionType=="CREATE")
  | .contractAddress
' "$BROADCAST" | tail -n 1)"
: "${BRIDGE_ADDRESS:?failed to extract AckiNackiBridge address from $BROADCAST}"
echo ">>> Deployed BRIDGE_ADDRESS = $BRIDGE_ADDRESS"

# ─── 4. Rewrite non-secret L${LEVEL}_config/env ───────────────────────────────
CFG_DIR="$PROVER_DIR/L${LEVEL}_config"
mkdir -p "$CFG_DIR/state" "$CFG_DIR/proofs" "$CFG_DIR/work_dir"

cat > "$CFG_DIR/env" <<EOF
# Generated by scripts/deploy_bridge_bundle.sh — do not hand-edit
# BRIDGE_BOOTSTRAP_SEQNO; re-run the script to regenerate anchors.
source "\$(dirname "\${BASH_SOURCE[0]}")/../shellnet.common"

BRIDGE_ADDRESS=$BRIDGE_ADDRESS
BRIDGE_BOOTSTRAP_SEQNO=$GENESIS_SEED_SEQNO
BRIDGE_ANCHOR_LEVEL=$LEVEL
EOF
echo ">>> Wrote $CFG_DIR/env"

# ─── 5. Archive stale state so the new bridge cold-start remains recoverable ─
STATE_ARCHIVE="$CFG_DIR/state.pre_deploy_$(date -u +%Y%m%dT%H%M%SZ)"
if compgen -G "$CFG_DIR/state/*.json" >/dev/null; then
  mkdir -p "$STATE_ARCHIVE"
  mv -- "$CFG_DIR/state"/*.json "$STATE_ARCHIVE/"
  echo ">>> Archived prior state in $STATE_ARCHIVE"
else
  echo ">>> No prior state JSON to archive"
fi

cat <<EOF

>>> Done. Next:
    cd $PROVER_DIR
    export BRIDGE_CONFIG_DIR=./L${LEVEL}_config
    set -a && source "\$BRIDGE_CONFIG_DIR/env" && set +a
    ./target/release/relayer --state "\$BRIDGE_CONFIG_DIR/relayer-state.json" daemon-live
EOF
