[package]
name = "layer-hashes-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
layer-hashes-update-halo2-circuit = { path = "../../layer-hashes-update-halo2-circuit/circuit" }
layer-hashes-block-data-gen = { path = "../../layer-hashes-update-halo2-circuit/block_data_gen" }
gosh-zk-snark-halo2-utils = { path = "../../gosh-zk-snark-halo2-utils" }
halo2-base = { git = "https://github.com/gosh-sh/halo2-lib-zkevm-sha256-and-bls12-381", branch = "main", default-features = false, features = ["halo2-axiom", "test-utils"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num-bigint = "0.4"
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
pse-poseidon = { git = "https://github.com/axiom-crypto/pse-poseidon.git" }
gosh-bls-verification = { git = "https://github.com/gosh-sh/gosh-halo2-crypto-lib" }
gosh-dense-balanced-tree = { git = "https://github.com/gosh-sh/gosh-halo2-crypto-lib" }

[features]
default = ["small-window"]
small-window = ["layer-hashes-update-halo2-circuit/small-window", "layer-hashes-block-data-gen/small-window"]

[patch.crates-io]
halo2-base = { git = "https://github.com/gosh-sh/halo2-lib-zkevm-sha256-and-bls12-381", branch = "main" }

[patch."https://github.com/gosh-sh/gosh-halo2-crypto-lib"]
gosh-sha256-chip = { path = "../../gosh-halo2-crypto-lib/sha256-chip" }
gosh-dense-balanced-tree = { path = "../../gosh-halo2-crypto-lib/dense-balanced-tree" }
gosh-bls-verification = { path = "../../gosh-halo2-crypto-lib/bls-verification" }

[profile.dev]
opt-level = 3

[[bin]]
name = "export-proof"
path = "src/export_proof.rs"

[[bin]]
name = "convert-proof"
path = "src/bin/convert_proof.rs"
