// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

// import "./Halo2Verifier.sol";  // Halo2Verifier is deployed as raw bytecode

/**
 * @title Halo2VerifierWrapper
 * @notice Wrapper around the generated Halo2Verifier to provide a user-friendly interface
 * @dev The Halo2Verifier is generated by scroll-tech/snark-verifier-sdk and uses assembly
 */
contract Halo2VerifierWrapper {
    address public immutable verifier;

    error InvalidProof();
    error InvalidPublicInputsCount();
    error InvalidRecipient();

    constructor(address _verifier) {
        verifier = _verifier;
    }

    /**
     * @notice Verify a withdrawal proof
     * @param proof The ZK proof bytes
     * @param publicInputs Array of public inputs: [nullifier, recipient, amount, root]
     * @return isValid Whether the proof is valid
     * @return nullifier The nullifier from the proof (first public input)
     */
    function verifyWithdrawalProof(
        bytes memory proof,
        uint256[] memory publicInputs
    ) external returns (bool isValid, bytes32 nullifier) {
        // Validate public inputs count
        if (publicInputs.length != 4) {
            return (false, bytes32(0));
        }

        // Validate recipient is not zero
        if (publicInputs[1] == 0) {
            return (false, bytes32(0));
        }

        // Validate proof is not empty
        if (proof.length == 0) {
            return (false, bytes32(0));
        }

        // The Halo2Verifier expects calldata in the format:
        // [public_input_0, public_input_1, ..., public_input_n, proof_bytes...]
        // We need to encode the public inputs followed by the proof
        bytes memory verifierCalldata = abi.encodePacked(
            bytes32(publicInputs[0]), // nullifier
            bytes32(publicInputs[1]), // recipient
            bytes32(publicInputs[2]), // amount
            bytes32(publicInputs[3]), // root
            proof
        );

        // Call the verifier
        (bool success, bytes memory result) = verifier.call(verifierCalldata);

        // The verifier returns true (0x01) if the proof is valid
        if (success && result.length > 0) {
            isValid = abi.decode(result, (bool));
        } else {
            isValid = false;
        }

        nullifier = bytes32(publicInputs[0]);
        return (isValid, nullifier);
    }

    /**
     * @notice Get the number of public inputs expected by the verifier
     * @return count The number of public inputs (always 4 for withdrawal circuit)
     */
    function getPublicInputsCount() external pure returns (uint256) {
        return 4;
    }
}

