// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @title IBridgeWithdrawalGroth16Verifier
/// @notice Interface for the gnark-generated Groth16 verifier with
///         `10 + NUM_LAYER_HASHES` public inputs (Circuit 4 v2 —
///         Bridge Withdrawal Prove, Phase B).
///
/// @dev Will be auto-generated by `gnark-wrappers/circuit-4/circuit-4 setup`
///      once the partner's v2 circuit (with `amount`, `recipient`, `dstChainId`,
///      `sender*` and `nullifier` lifted to public inputs) lands. Until then
///      the on-chain adapter `BridgeWithdrawalVerifier.sol` is built against
///      this interface and exercised through a mock implementing it.
///
///      Phase B is a **hard ABI break** vs Phase A's `IBridgeEventGroth16Verifier`
///      (`103 → 110` public inputs, indices shifted). Both interfaces coexist
///      during migration; Phase A retires when the v2 circuit + verifier are
///      adopted in production. See `docs/an_partner_circuit4_alina_replies_2026-05-21.md`
///      for the layout rationale.
///
///      Public-input layout (110 BN254 Fr elements; matches Alina's
///      2026-05-21 decoded ABI):
///      ```
///      [  0]      tokenId         (uint32 packed BE from event body[54..58))
///      [  1]      amount          (uint128)
///      [  2]      recipientHi     (Fr; top half of 20-byte EVM address)
///      [  3]      recipientLo     (Fr; bottom half of 20-byte EVM address)
///      [  4]      dstChainId      (uint64; must equal `block.chainid` on Ethereum)
///      [  5]      senderDappFr    (Fr; AN-side sender dApp identifier)
///      [  6]      senderAccFr     (Fr; AN-side sender account identifier)
///      [  7]      dappFr          (Fr; bridge dApp identifier on AN side)
///      [  8]      accFr           (Fr; bridge account identifier on AN side)
///      [  9]      nullifier       (Fr; Poseidon(block_id, tokenId, amount,
///                                            recipient, senderDapp, senderAcc))
///      [ 10..109] layerHashes     (100 candidate top-of-chain anchors; the
///                                 circuit privately binds to one of them via
///                                 `hash_choice_index`)
///      ```
interface IBridgeWithdrawalGroth16Verifier {
    function verifyProof(uint256[8] calldata proof, uint256[110] calldata input) external view;
}
