// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @title IBridgeEventGroth16Verifier
/// @notice Interface for the gnark-generated Groth16 verifier with
///         `3 + NUM_LAYER_HASHES` public inputs (Circuit 4 — Bridge Event
///         Prove).
///
/// @dev Will be auto-generated by `gnark-wrappers/circuit-4/circuit-4 setup`
///      and committed as `BridgeEventGroth16VerifierGenerated.sol` once the
///      partner circuit binary stabilises (Phase B of the Phase A/B split
///      documented in `docs/circuit_4_open_questions.md`). Until then the
///      adapter `BridgeEventVerifier.sol` is built against this interface
///      and unit-tested through a mock implementing it.
///
///      Public-input layout (103 BN254 Fr elements):
///      ```
///      [0]         tokenId        (uint32 packed BE from event body[54..58))
///      [1]         dappFr         (Fr-encoded AN-side bridge dApp id)
///      [2]         accFr          (Fr-encoded AN-side bridge account id)
///      [3..=102]   layerHashes    100 candidate latest-layer hashes; circuit
///                                 binds (privately) to exactly one of them
///                                 via `hash_choice_index` — privacy.
///      ```
interface IBridgeEventGroth16Verifier {
    function verifyProof(uint256[8] calldata proof, uint256[103] calldata input) external view;
}
