// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @title IFallbackGroth16Verifier
/// @notice Interface for the gnark-generated Groth16 verifier with 4 public
///         inputs (Circuit 1B / Fallback attestation).
/// @dev The actual implementation is auto-generated by gnark setup
///      (`crates/bridge-prover-orchestrator/gnark-wrappers/circuit-1b/`) and
///      is committed as `FallbackGroth16VerifierGenerated.sol`. The adapter
///      `FallbackVerifier.sol` wraps this interface in the bridge-friendly
///      shape `verifyFallbackAttestation(...)`.
interface IFallbackGroth16Verifier {
    function verifyProof(uint256[8] calldata proof, uint256[4] calldata input) external view;
}
