// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @title ILayerHashesGroth16Verifier
/// @notice Interface for the gnark-generated Groth16 verifier with 14 public
///         inputs (Circuit 2 — Layer Hashes Movement).
/// @dev Auto-generated by `gnark-wrappers/circuit-2/circuit-2 setup` and
///      committed as `LayerHashesGroth16VerifierGenerated.sol`. The adapter
///      `LayerHashesMovementVerifier.sol` wraps this in the bridge-friendly
///      shape `verifyLayerHashesMovement(...)`. Public-input shape:
///      ```
///      [0]      block_id
///      [1]      bk_set_poseidon
///      [2]      num_layers
///      [3..=12] layer_hash_frs[0..10]
///      [13]     prev_max_level_layer_hash
///      ```
interface ILayerHashesGroth16Verifier {
    function verifyProof(uint256[8] calldata proof, uint256[14] calldata input) external view;
}
