// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @title IPrimaryGroth16Verifier
/// @notice Interface for the gnark-generated Groth16 verifier with 4 public
///         inputs (Circuit 1A / Primary attestation).
/// @dev The actual implementation is auto-generated by gnark setup
///      (`crates/bridge-prover-orchestrator/gnark-wrappers/circuit-1a/`) and
///      is committed as `PrimaryGroth16VerifierGenerated.sol`. The adapter
///      `PrimaryVerifier.sol` wraps this interface in the bridge-friendly
///      shape `verifyPrimaryAttestation(...)`. Shape is identical to
///      `IFallbackGroth16Verifier` because both circuits expose the same 4
///      public inputs, but the verification keys differ (different Groth16
///      setups), so the contracts cannot be shared.
interface IPrimaryGroth16Verifier {
    function verifyProof(uint256[8] calldata proof, uint256[4] calldata input) external view;
}
