// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @title ILayerHashGroth16Verifier
/// @notice Interface for the gnark-generated Groth16 verifier with 13 public inputs.
/// @dev The actual implementation is auto-generated by gnark setup and deployed
///      separately. This interface is used by LayerHashVerifier to call it.
interface ILayerHashGroth16Verifier {
    function verifyProof(uint256[8] calldata proof, uint256[13] calldata input) external view;
}
