#!/usr/bin/env bash
# Deploy or redeploy the shellnet E2E bridge bundle end-to-end.
#
# Runs `compute_bridge_anchors --at-head` against live shellnet to derive
# GENESIS_LAST_SEEN_BLOCK_SEQNO / GENESIS_PREV_MAX_LEVEL_LAYER_HASH /
# GENESIS_BK_SET_COMMITMENT, deploys the 6-contract bundle via forge, extracts
# BRIDGE_ADDRESS from the broadcast record, rewrites L${LEVEL}_config/env, and
# wipes stale prover state so the daemon cold-starts on the new anchor.
#
# Idempotent: a second run regenerates anchors against fresh chain head and
# redeploys — exactly the flow described in
# crates/bridge-relayer-daemon/docs/live_relayer_bridge_verifyBlock_runbook.md §3.
#
# Usage:
#   LEVEL=1 PRIVATE_KEY=<burner> ./scripts/deploy_bridge_bundle.sh   # L1 anchor
#   LEVEL=2 PRIVATE_KEY=<burner> ./scripts/deploy_bridge_bundle.sh   # L2 anchor
#
# Inputs (env):
#   LEVEL                      1 or 2 (required)
#   PRIVATE_KEY                Sepolia burner from runbook §1 (required)
#   SEPOLIA_RPC_URL            default: https://ethereum-sepolia-rpc.publicnode.com
#   BRIDGE_GQL_ENDPOINT        default: https://shellnet.ackinacki.org/graphql
#   BRIDGE_BK_SET_CONFIG       default: ./bk_set.shellnet.json
#                              (relative to crates/an-bridge-prover)
#   WITHDRAW_ACC_FR            default: 0x1a1a...1a1a (placeholder — replace for
#                              real withdraws)
set -euo pipefail

: "${LEVEL:?set LEVEL=1 or LEVEL=2}"
: "${PRIVATE_KEY:?set PRIVATE_KEY=<sepolia burner>}"
SEPOLIA_RPC_URL="${SEPOLIA_RPC_URL:-https://ethereum-sepolia-rpc.publicnode.com}"
BRIDGE_GQL_ENDPOINT="${BRIDGE_GQL_ENDPOINT:-https://shellnet.ackinacki.org/graphql}"
BRIDGE_BK_SET_CONFIG="${BRIDGE_BK_SET_CONFIG:-./bk_set.shellnet.json}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PROVER_DIR="$REPO_ROOT/crates/an-bridge-prover"
CONTRACTS_DIR="$REPO_ROOT/contracts/ethereum"
GENESIS_ENV="$(mktemp -t genesis.XXXXXX.env)"
trap 'rm -f "$GENESIS_ENV"' EXIT

# ─── 1. Derive genesis anchors from live shellnet chain head ──────────────────
echo ">>> Computing genesis anchors (level=$LEVEL) against $BRIDGE_GQL_ENDPOINT"
cd "$PROVER_DIR/bridge-prover-lib"
BRIDGE_GQL_ENDPOINT="$BRIDGE_GQL_ENDPOINT" \
BRIDGE_BK_SET_CONFIG="$PROVER_DIR/${BRIDGE_BK_SET_CONFIG#./}" \
cargo run --release --quiet --bin compute_bridge_anchors -- \
  --at-head --level "$LEVEL" \
  > "$GENESIS_ENV"

echo ">>> Derived anchors:"
cat "$GENESIS_ENV"
set -a && source "$GENESIS_ENV" && set +a

# CRITICAL RENAME: compute_bridge_anchors emits GENESIS_SEED_SEQNO;
# DeployShellnetE2EBridge.s.sol reads GENESIS_LAST_SEEN_BLOCK_SEQNO via
# vm.envOr(..., 0) — without this alias the constructor silently pins 0.
export GENESIS_LAST_SEEN_BLOCK_SEQNO="$GENESIS_SEED_SEQNO"

# ─── 2. Deploy the 6-contract bundle ──────────────────────────────────────────
cd "$CONTRACTS_DIR"
export PRIVATE_KEY
export WIRE_WITHDRAW_BY_PROOF=true
export WITHDRAW_ACC_FR="${WITHDRAW_ACC_FR:-0x1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a}"

echo ">>> forge script DeployShellnetE2EBridge (chain 11155111)"
forge script script/DeployShellnetE2EBridge.s.sol:DeployShellnetE2EBridge \
  --rpc-url "$SEPOLIA_RPC_URL" --broadcast --slow

# ─── 3. Extract BRIDGE_ADDRESS from the broadcast record ──────────────────────
BROADCAST="$CONTRACTS_DIR/broadcast/DeployShellnetE2EBridge.s.sol/11155111/run-latest.json"
BRIDGE_ADDRESS="$(jq -r '
  .transactions[]
  | select(.contractName=="AckiNackiBridge" and .transactionType=="CREATE")
  | .contractAddress
' "$BROADCAST" | tail -n 1)"
: "${BRIDGE_ADDRESS:?failed to extract AckiNackiBridge address from $BROADCAST}"
echo ">>> Deployed BRIDGE_ADDRESS = $BRIDGE_ADDRESS"

# ─── 4. Rewrite L${LEVEL}_config/env atomically ───────────────────────────────
CFG_DIR="$PROVER_DIR/L${LEVEL}_config"
mkdir -p "$CFG_DIR/state" "$CFG_DIR/proofs" "$CFG_DIR/work_dir"

if [ ! -f "$PROVER_DIR/shellnet.common" ]; then
  cat > "$PROVER_DIR/shellnet.common" <<EOF
RPC_URL=$SEPOLIA_RPC_URL
RELAYER_PRIVATE_KEY=$PRIVATE_KEY
BRIDGE_GQL_ENDPOINT=$BRIDGE_GQL_ENDPOINT
BRIDGE_BK_SET_CONFIG=$BRIDGE_BK_SET_CONFIG
BRIDGE_PARAMS_DIR=./params
BRIDGE_AGGREGATOR_DIR=../bridge-evm-aggregator
BRIDGE_VERIFIERS_DIR=../../contracts/ethereum/verifiers
EOF
  echo ">>> Wrote fresh $PROVER_DIR/shellnet.common"
fi

cat > "$CFG_DIR/env" <<EOF
# Generated by scripts/deploy_bridge_bundle.sh — do not hand-edit
# BRIDGE_BOOTSTRAP_SEQNO; re-run the script to regenerate anchors.
source "\$(dirname "\${BASH_SOURCE[0]}")/../shellnet.common"

BRIDGE_ADDRESS=$BRIDGE_ADDRESS
BRIDGE_BOOTSTRAP_SEQNO=$GENESIS_SEED_SEQNO
BRIDGE_ANCHOR_LEVEL=$LEVEL
EOF
echo ">>> Wrote $CFG_DIR/env"

# ─── 5. Wipe stale prover state so daemon cold-starts on the new anchor ───────
rm -f "$CFG_DIR/state"/*.json
echo ">>> Cleared $CFG_DIR/state/*.json (fresh cold-start)"

cat <<EOF

>>> Done. Next:
    cd $PROVER_DIR
    export BRIDGE_CONFIG_DIR=./L${LEVEL}_config
    set -a && source "\$BRIDGE_CONFIG_DIR/env" && set +a
    ./target/release/relayer daemon-live
EOF
