//! Native Poseidon-based Fiat–Shamir transcript for Halo2 SHPLONK proofs.
//!
//! This is the orchestrator-side counterpart to `snark-verifier-sdk`'s
//! `PoseidonTranscript<NativeLoader, _>`. Both produce the SAME proof bytes for
//! the same circuit and witness because they share:
//!
//! - The exact same `OptimizedPoseidonSpec` (`T=3`, `RATE=2`, `R_F=8`,
//!   `R_P=57`, `SECURE_MDS=0`). These constants live in `halo2-base`'s
//!   `poseidon::hasher::spec` module, which the gosh fork and the axiom-crypto
//!   fork carry verbatim (both derived from PSE upstream).
//! - The same absorption order — scalars are absorbed as one field element; EC
//!   points are absorbed as `[fe_to_fe(x), fe_to_fe(y)]` (base → scalar field
//!   reduction); challenges are squeezed by a buffered permutation.
//! - The same on-wire encoding — scalars use `PrimeField::to_repr`/`from_repr`
//!   (32 LE bytes for BN254), EC points use
//!   `CurveAffine::to_bytes`/`from_bytes`.
//!
//! Byte-for-byte compatibility with `snark-verifier-sdk` is what lets a proof
//! produced by `bridge-prover-orchestrator` (which builds against the gosh
//! halo2-lib fork) be fed without modification into an `AggregationCircuit`
//! living in `crates/bridge-evm-aggregator/` (which builds against
//! axiom-crypto/halo2-lib). Without this we would have to re-prove inside the
//! aggregator's workspace, but the partner's bridge-circuit code is tied to
//! the gosh fork's chips (BLS / SHA / dense Merkle), so re-proving is not an
//! option.
//!
//! ## Why we vendor rather than depend on `snark-verifier`
//!
//! `snark-verifier` declares `halo2-base` (axiom-crypto fork) as a
//! non-optional dependency. The orchestrator pins `halo2-base` to the gosh
//! fork; the two cannot coexist in one cargo unit. So we re-implement the
//! ~80 lines of native Poseidon permutation logic from
//! `snark-verifier/src/util/hash/poseidon.rs` here, parameterised over
//! `OptimizedPoseidonSpec` (which IS available in gosh halo2-base under the
//! same module path).
//!
//! ## What this transcript is NOT used for
//!
//! - `ZKHALO2VERIFYWITHVK` on Acki Nacki side: that opcode commits to Blake2b
//!   and rejects anything else. Use [`crate::prover::generate_fallback_proof`]
//!   (default Blake2b path).
//! - On-chain Yul verifier on Ethereum side: the Yul verifier generated by
//!   `snark-verifier-sdk::gen_evm_verifier_shplonk` uses `EvmTranscript`
//!   (Keccak), NOT Poseidon. The Poseidon transcript here feeds the **inner**
//!   SNARK that the aggregator verifies in-circuit; the **outer** aggregator
//!   proof then uses Keccak/`EvmTranscript`.
//!
//! See `docs/r15_snark_verifier_roadmap.md` for the full pipeline (M3+).

use std::{
    io::{self, Read, Write},
    mem,
};

use halo2_base::{
    halo2_proofs::{
        halo2curves::{
            bn256::{Fr, G1Affine},
            ff::{FromUniformBytes, PrimeField},
            group::GroupEncoding,
            CurveAffine,
        },
        transcript::{
            EncodedChallenge, Transcript, TranscriptRead, TranscriptReadBuffer, TranscriptWrite,
            TranscriptWriterBuffer,
        },
    },
    poseidon::hasher::{mds::SparseMDSMatrix, spec::OptimizedPoseidonSpec},
};
use num_bigint::BigUint;

// ---------------------------------------------------------------------------
// Poseidon-T3-RATE2 spec constants
// ---------------------------------------------------------------------------
//
// These MUST equal `snark-verifier-sdk`'s `T`, `RATE`, `R_F`, `R_P`,
// `SECURE_MDS` (see `snark-verifier-sdk/src/halo2.rs` lines 54-58 in
// v0.1.7-git) or the aggregator's in-circuit verifier will derive different
// challenges and the inner SNARK will fail to verify.

/// Width of the Poseidon state.
pub const POSEIDON_T: usize = 3;
/// Rate (number of absorbed elements per permutation).
pub const POSEIDON_RATE: usize = 2;
/// Number of full rounds (half before, half after the partial-round chunk).
pub const POSEIDON_R_F: usize = 8;
/// Number of partial rounds.
pub const POSEIDON_R_P: usize = 57;
/// `SECURE_MDS = 0` skips secure-MDS replacement. snark-verifier-sdk also
/// uses 0; this is fine because the auto-generated MDS for `T=3, RATE=2,
/// Fr` over BN254 is known to be secure (matches scroll-tech's choice).
pub const POSEIDON_SECURE_MDS: usize = 0;

// ---------------------------------------------------------------------------
// Native Poseidon hasher (L = F)
// ---------------------------------------------------------------------------
//
// Mirrors `snark_verifier::util::hash::poseidon::Poseidon<F, F, T, RATE>`
// (the `NativeLoader` instantiation).

/// Native Poseidon-128 sponge state used to derive Fiat–Shamir challenges.
#[derive(Clone, Debug)]
struct NativePoseidon {
    spec: OptimizedPoseidonSpec<Fr, POSEIDON_T, POSEIDON_RATE>,
    state: [Fr; POSEIDON_T],
    buf: Vec<Fr>,
}

impl NativePoseidon {
    fn new() -> Self {
        // Variable-Input-Length Hashing capacity (Section 4.2 of
        // https://eprint.iacr.org/2019/458.pdf): `2^64 + (o-1)`, with output
        // length `o = 1`.
        let mut state = [Fr::zero(); POSEIDON_T];
        state[0] = Fr::from_u128(1u128 << 64);
        Self {
            spec: OptimizedPoseidonSpec::new::<POSEIDON_R_F, POSEIDON_R_P, POSEIDON_SECURE_MDS>(),
            state,
            buf: Vec::new(),
        }
    }

    fn update(&mut self, elements: &[Fr]) {
        self.buf.extend_from_slice(elements);
    }

    fn squeeze(&mut self) -> Fr {
        let buf = mem::take(&mut self.buf);
        let exact = buf.len().is_multiple_of(POSEIDON_RATE);

        for chunk in buf.chunks(POSEIDON_RATE) {
            self.permutation(chunk);
        }
        if exact {
            self.permutation(&[]);
        }

        // Same convention as snark-verifier: output `state[1]`, not `state[0]`.
        self.state[1]
    }

    fn permutation(&mut self, inputs: &[Fr]) {
        let r_f = self.spec.r_f() / 2;
        let mds = self.spec.mds_matrices().mds().as_ref();
        let pre_sparse_mds = self.spec.mds_matrices().pre_sparse_mds().as_ref();
        let sparse_matrices = self.spec.mds_matrices().sparse_matrices();

        // First half of the full rounds (with input absorption baked into
        // round 0 via `absorb_with_pre_constants`).
        let constants_start = self.spec.constants().start();
        absorb_with_pre_constants(&mut self.state, inputs, &constants_start[0]);
        for constants in constants_start.iter().skip(1).take(r_f - 1) {
            sbox_full(&mut self.state, constants);
            apply_mds(&mut self.state, mds);
        }
        sbox_full(&mut self.state, constants_start.last().unwrap());
        apply_mds(&mut self.state, pre_sparse_mds);

        // Partial rounds.
        let constants_partial = self.spec.constants().partial();
        for (constant, sparse_mds) in constants_partial.iter().zip(sparse_matrices.iter()) {
            sbox_part(&mut self.state, constant);
            apply_sparse_mds(&mut self.state, sparse_mds);
        }

        // Second half of the full rounds.
        let constants_end = self.spec.constants().end();
        for constants in constants_end.iter() {
            sbox_full(&mut self.state, constants);
            apply_mds(&mut self.state, mds);
        }
        sbox_full(&mut self.state, &[Fr::zero(); POSEIDON_T]);
        apply_mds(&mut self.state, mds);
    }
}

// ---------------------------------------------------------------------------
// Permutation primitives (verbatim port of
// snark-verifier::util::hash::poseidon for L=F)
// ---------------------------------------------------------------------------

fn sbox_full(state: &mut [Fr; POSEIDON_T], constants: &[Fr; POSEIDON_T]) {
    for (x, c) in state.iter_mut().zip(constants.iter()) {
        let x2 = *x * *x;
        let x4 = x2 * x2;
        *x = *x * x4 + *c;
    }
}

fn sbox_part(state: &mut [Fr; POSEIDON_T], constant: &Fr) {
    let x = &mut state[0];
    let x2 = *x * *x;
    let x4 = x2 * x2;
    *x = *x * x4 + *constant;
}

fn absorb_with_pre_constants(
    state: &mut [Fr; POSEIDON_T],
    inputs: &[Fr],
    pre_constants: &[Fr; POSEIDON_T],
) {
    assert!(inputs.len() < POSEIDON_T, "inputs must fit in RATE slots");

    // Capacity element only takes the constant.
    state[0] += pre_constants[0];

    for ((x, c), input) in state
        .iter_mut()
        .zip(pre_constants.iter())
        .skip(1)
        .zip(inputs.iter())
    {
        *x += *input + *c;
    }

    let offset = inputs.len() + 1;
    for (i, (x, c)) in state
        .iter_mut()
        .zip(pre_constants.iter())
        .skip(offset)
        .enumerate()
    {
        *x += if i == 0 { Fr::one() + *c } else { *c };
    }
}

fn apply_mds(state: &mut [Fr; POSEIDON_T], mds: &[[Fr; POSEIDON_T]; POSEIDON_T]) {
    let mut out = [Fr::zero(); POSEIDON_T];
    for i in 0..POSEIDON_T {
        for j in 0..POSEIDON_T {
            out[i] += mds[i][j] * state[j];
        }
    }
    *state = out;
}

fn apply_sparse_mds(
    state: &mut [Fr; POSEIDON_T],
    mds: &SparseMDSMatrix<Fr, POSEIDON_T, POSEIDON_RATE>,
) {
    let mut out = [Fr::zero(); POSEIDON_T];

    // First row of the sparse MDS is a full row.
    let row = mds.row();
    for j in 0..POSEIDON_T {
        out[0] += row[j] * state[j];
    }

    // The remaining rows form `[col_hat | identity]` (column-then-identity),
    // so out[i] = state[i] + col_hat[i-1] * state[0] for i >= 1.
    let col_hat = mds.col_hat();
    for i in 1..POSEIDON_T {
        out[i] = state[i] + col_hat[i - 1] * state[0];
    }

    *state = out;
}

// ---------------------------------------------------------------------------
// Base → scalar field reduction (mirror of
// snark-verifier::util::arithmetic::fe_to_fe)
// ---------------------------------------------------------------------------

fn fq_to_fr(fe: <G1Affine as CurveAffine>::Base) -> Fr {
    // BN254 base and scalar fields are both ~254 bits; the standard reduction
    // is `repr_LE mod p_scalar`. snark-verifier does exactly this via
    // `BigUint::from_bytes_le(...) % modulus::<Fr>()`.
    let repr = fe.to_repr();
    let bytes = repr.as_ref();
    let big = BigUint::from_bytes_le(bytes);
    let modulus = fr_modulus();
    let reduced = big % modulus;
    let reduced_bytes = reduced.to_bytes_le();

    let mut out_repr = <Fr as PrimeField>::Repr::default();
    let len = reduced_bytes.len().min(out_repr.as_ref().len());
    out_repr.as_mut()[..len].copy_from_slice(&reduced_bytes[..len]);
    Fr::from_repr(out_repr).expect("reduced bytes fit in Fr by construction")
}

fn fr_modulus() -> BigUint {
    // BN254 scalar field modulus: read it once from `-Fr::one() + 1` to avoid
    // hard-coding bytes that could go stale if halo2curves ever flipped
    // endianness.
    let neg_one = -Fr::one();
    let repr = neg_one.to_repr();
    let bytes = repr.as_ref();
    BigUint::from_bytes_le(bytes) + 1u32
}

// ---------------------------------------------------------------------------
// Encoded challenge (mirrors snark-verifier::ChallengeScalar)
// ---------------------------------------------------------------------------

/// `EncodedChallenge` whose carrier is a native scalar field element. The
/// transcript squeezes a `Fr` directly from Poseidon (no extra 512-bit
/// expansion à la Blake2b's `Challenge255`), then wraps it here.
#[derive(Clone, Copy, Debug)]
pub struct PoseidonChallenge(Fr);

impl EncodedChallenge<G1Affine> for PoseidonChallenge {
    type Input = Fr;

    fn new(input: &Fr) -> Self {
        PoseidonChallenge(*input)
    }

    fn get_scalar(&self) -> Fr {
        self.0
    }
}

// ---------------------------------------------------------------------------
// PoseidonRead / PoseidonWrite
// ---------------------------------------------------------------------------

/// Poseidon transcript reader. Use this when the verifier reads a proof
/// produced by [`PoseidonWrite`] or by snark-verifier-sdk's
/// `PoseidonTranscript<NativeLoader, _>`.
pub struct PoseidonRead<R: Read> {
    hasher: NativePoseidon,
    stream: R,
}

impl<R: Read> PoseidonRead<R> {
    pub fn init(stream: R) -> Self {
        Self {
            hasher: NativePoseidon::new(),
            stream,
        }
    }
}

impl<R: Read> Transcript<G1Affine, PoseidonChallenge> for PoseidonRead<R> {
    fn squeeze_challenge(&mut self) -> PoseidonChallenge {
        PoseidonChallenge::new(&self.hasher.squeeze())
    }

    fn common_point(&mut self, ec_point: G1Affine) -> io::Result<()> {
        common_ec_point(&mut self.hasher, ec_point)
    }

    fn common_scalar(&mut self, scalar: Fr) -> io::Result<()> {
        self.hasher.update(&[scalar]);
        Ok(())
    }
}

impl<R: Read> TranscriptRead<G1Affine, PoseidonChallenge> for PoseidonRead<R> {
    fn read_point(&mut self) -> io::Result<G1Affine> {
        let mut data = <G1Affine as GroupEncoding>::Repr::default();
        self.stream.read_exact(data.as_mut())?;
        let ec_point: G1Affine = Option::<G1Affine>::from(G1Affine::from_bytes(&data))
            .ok_or_else(|| io::Error::other("invalid EC point encoding in Poseidon transcript"))?;
        Transcript::<G1Affine, PoseidonChallenge>::common_point(self, ec_point)?;
        Ok(ec_point)
    }

    fn read_scalar(&mut self) -> io::Result<Fr> {
        let mut data = <Fr as PrimeField>::Repr::default();
        self.stream.read_exact(data.as_mut())?;
        let scalar: Fr = Fr::from_repr(data)
            .into_option()
            .ok_or_else(|| io::Error::other("invalid scalar encoding in Poseidon transcript"))?;
        Transcript::<G1Affine, PoseidonChallenge>::common_scalar(self, scalar)?;
        Ok(scalar)
    }
}

impl<R: Read> TranscriptReadBuffer<R, G1Affine, PoseidonChallenge> for PoseidonRead<R>
where
    Fr: FromUniformBytes<64>,
{
    fn init(reader: R) -> Self {
        Self::init(reader)
    }
}

/// Poseidon transcript writer. The proof bytes emitted by `finalize()` are
/// the input to `PoseidonRead::init` (or to snark-verifier-sdk's
/// `PoseidonTranscript<NativeLoader, _>`).
pub struct PoseidonWrite<W: Write> {
    hasher: NativePoseidon,
    stream: W,
}

impl<W: Write> PoseidonWrite<W> {
    pub fn init(stream: W) -> Self {
        Self {
            hasher: NativePoseidon::new(),
            stream,
        }
    }

    pub fn finalize(self) -> W {
        self.stream
    }
}

impl<W: Write> Transcript<G1Affine, PoseidonChallenge> for PoseidonWrite<W> {
    fn squeeze_challenge(&mut self) -> PoseidonChallenge {
        PoseidonChallenge::new(&self.hasher.squeeze())
    }

    fn common_point(&mut self, ec_point: G1Affine) -> io::Result<()> {
        common_ec_point(&mut self.hasher, ec_point)
    }

    fn common_scalar(&mut self, scalar: Fr) -> io::Result<()> {
        self.hasher.update(&[scalar]);
        Ok(())
    }
}

impl<W: Write> TranscriptWrite<G1Affine, PoseidonChallenge> for PoseidonWrite<W> {
    fn write_point(&mut self, ec_point: G1Affine) -> io::Result<()> {
        Transcript::<G1Affine, PoseidonChallenge>::common_point(self, ec_point)?;
        let data = ec_point.to_bytes();
        self.stream.write_all(data.as_ref())
    }

    fn write_scalar(&mut self, scalar: Fr) -> io::Result<()> {
        Transcript::<G1Affine, PoseidonChallenge>::common_scalar(self, scalar)?;
        let data = scalar.to_repr();
        self.stream.write_all(data.as_ref())
    }
}

impl<W: Write> TranscriptWriterBuffer<W, G1Affine, PoseidonChallenge> for PoseidonWrite<W>
where
    Fr: FromUniformBytes<64>,
{
    fn init(writer: W) -> Self {
        Self::init(writer)
    }

    fn finalize(self) -> W {
        self.finalize()
    }
}

// ---------------------------------------------------------------------------
// Common EC-point absorption helper
// ---------------------------------------------------------------------------

fn common_ec_point(hasher: &mut NativePoseidon, ec_point: G1Affine) -> io::Result<()> {
    let coords = Option::<halo2_base::halo2_proofs::halo2curves::Coordinates<G1Affine>>::from(
        ec_point.coordinates(),
    )
    .ok_or_else(|| io::Error::other("invalid EC point coordinates"))?;
    let x = fq_to_fr(*coords.x());
    let y = fq_to_fr(*coords.y());
    hasher.update(&[x, y]);
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// `squeeze_challenge` on an empty transcript must be deterministic — same
    /// state, same output across two independent constructions. Guards
    /// against accidental randomness in spec generation.
    #[test]
    fn empty_squeeze_is_deterministic() {
        let mut a = NativePoseidon::new();
        let mut b = NativePoseidon::new();
        assert_eq!(a.squeeze(), b.squeeze());
    }

    /// Two writers fed the same scalars must produce identical proof bytes
    /// AND identical squeezed challenges — i.e. the transcript state evolves
    /// deterministically from the inputs.
    #[test]
    fn write_then_read_round_trip_scalars() {
        let xs: Vec<Fr> = (0..7).map(|i| Fr::from(i as u64 + 1)).collect();

        let mut writer = PoseidonWrite::init(Vec::<u8>::new());
        for s in &xs {
            writer.write_scalar(*s).unwrap();
        }
        let challenge_w: Fr = writer.squeeze_challenge().get_scalar();
        let bytes = writer.finalize();

        // Each scalar serialises to 32 bytes.
        assert_eq!(bytes.len(), xs.len() * 32);

        let mut reader = PoseidonRead::init(bytes.as_slice());
        let mut read_back = Vec::with_capacity(xs.len());
        for _ in &xs {
            read_back.push(reader.read_scalar().unwrap());
        }
        let challenge_r: Fr = reader.squeeze_challenge().get_scalar();

        assert_eq!(read_back, xs);
        assert_eq!(challenge_w, challenge_r);
    }

    /// EC points absorb as the (x,y) base-field coordinates reduced to Fr.
    /// We verify a write/read round-trip recovers identical points and
    /// identical post-state challenges.
    #[test]
    fn write_then_read_round_trip_points() {
        use halo2_base::halo2_proofs::halo2curves::{
            bn256::G1,
            group::{Curve, Group},
        };
        use rand::SeedableRng;

        let mut rng = rand::rngs::StdRng::seed_from_u64(0xC0FFEE);
        let points: Vec<G1Affine> = (0..5)
            .map(|_| {
                let p = G1::random(&mut rng);
                p.to_affine()
            })
            .collect();

        let mut writer = PoseidonWrite::init(Vec::<u8>::new());
        for p in &points {
            writer.write_point(*p).unwrap();
        }
        let challenge_w: Fr = writer.squeeze_challenge().get_scalar();
        let bytes = writer.finalize();
        assert_eq!(bytes.len(), points.len() * 32); // compressed G1Affine = 32 B

        let mut reader = PoseidonRead::init(bytes.as_slice());
        let mut read_back = Vec::with_capacity(points.len());
        for _ in &points {
            read_back.push(reader.read_point().unwrap());
        }
        let challenge_r: Fr = reader.squeeze_challenge().get_scalar();

        assert_eq!(read_back, points);
        assert_eq!(challenge_w, challenge_r);
    }

    /// Tampered bytes flip the read scalars and therefore the squeezed
    /// challenges — a sanity check that the transcript is actually using
    /// the read data (not silently ignoring it).
    #[test]
    fn tampered_proof_changes_challenge() {
        let xs: Vec<Fr> = (0..3).map(|i| Fr::from(i as u64 + 1)).collect();

        let mut writer = PoseidonWrite::init(Vec::<u8>::new());
        for s in &xs {
            writer.write_scalar(*s).unwrap();
        }
        let challenge_clean: Fr = writer.squeeze_challenge().get_scalar();
        let mut bytes = writer.finalize();

        // Flip a single bit deep inside the second scalar (still a valid Fr
        // element — flipping low bit can never overflow the modulus).
        bytes[32] ^= 0x01;

        let mut reader = PoseidonRead::init(bytes.as_slice());
        for _ in &xs {
            let _ = reader.read_scalar().unwrap();
        }
        let challenge_tampered: Fr = reader.squeeze_challenge().get_scalar();

        assert_ne!(challenge_clean, challenge_tampered);
    }

    /// Construct the spec twice and check round-constant determinism. This
    /// guards against any future surprise where round-constant generation
    /// pulls entropy.
    #[test]
    fn spec_is_deterministic() {
        let a: OptimizedPoseidonSpec<Fr, POSEIDON_T, POSEIDON_RATE> =
            OptimizedPoseidonSpec::new::<POSEIDON_R_F, POSEIDON_R_P, POSEIDON_SECURE_MDS>();
        let b: OptimizedPoseidonSpec<Fr, POSEIDON_T, POSEIDON_RATE> =
            OptimizedPoseidonSpec::new::<POSEIDON_R_F, POSEIDON_R_P, POSEIDON_SECURE_MDS>();
        assert_eq!(a.constants().start(), b.constants().start());
        assert_eq!(a.constants().partial(), b.constants().partial());
        assert_eq!(a.constants().end(), b.constants().end());
    }
}
